- package.json
- src/frontend/App.tsx
- src/frontend/context/AppContext.ts
- src/frontend/komponenter/DataViewer.tsx
- src/frontend/typer/ressurs.ts
- src/frontend/utils/fetch.ts
- tsconfig.json
- yarn.lock
Vi ønsker å bruke Ressurs i frontend for å kunne bruke dataviewer-komponenten og for å få typede responser.
Eksempel på bruk:
```js
const { request } = useApp();
const [nyBehandlingRessurs, settNyBehandlingRessurs] = useState<Ressurs<string>>(byggTomRessurs());
const opprettBehandling = () => {
request<string, { personIdent: string }>(`/api/sak/test/opprett-behandling`, 'POST', {
personIdent: personIdent,
}).then(settNyBehandlingRessurs);
};
```
Denne kan utvides med mer funksjonalitet, men dette er en start for å kunne gjøre enkle fetch kall 🤠 
**Hva mangler?**
* Håndtering av 401
* Håndtering av IKKE_TILGANG
* Logging ved feil
> ✨  AppContext og fetch

- src/frontend/Sider/Behandling/BehandlingContainer.tsx
- src/frontend/Sider/Behandling/BehandlingInnhold.tsx
- src/frontend/context/BehandlingContext.ts
- src/frontend/hooks/useRerunnableEffect.ts
- src/frontend/utils/fetch.ts
Vi ønsker å ha `behandling` tilgjengelig i context for å slippe å sende den som props. 
Litt usikker på hvordan vi vil gjøre dette, men la det opp litt annerledes enn i ef-sak.
Forskjellen på denne og ef-saks hook:
- Denne returnerer `Behandling`
- ef-sak returnerer `Ressurs<Behandling>`
Det betyr at hele behandlingscontaineren re-rendres hver gang man kjører `hentBehandling.rerun()` Fordelen er at komponentene i containeren kan bruke `behandling` direkte, uten å forholde seg til ressurs. Hva tenker dere om det @sarahjelle @blommish ?
> ✨  Behandlingscontext

- src/frontend/Sider/Behandling/Fanemeny/faner.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/VedtakOgBeregningBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Felles/SelectVedtaksresultat.tsx
- src/frontend/context/BehandlingContext.ts
- src/frontend/komponenter/Skjema/Lesefelt.tsx
- src/frontend/komponenter/Skjema/Select.tsx
- src/frontend/typer/behandling/behandlingResultat.ts
Start på vedtak og beregning. 
Skal være mulig å velge ønsket resultat og rendre innhold basert på valg. 
OBS: mest sannsynlig forsvinner funksjonen med switch dersom vi får inn en dataviewer
> Vedtak beregning - velg resultat for behandling

- src/frontend/Sider/Behandling/Fanemeny/Fane.tsx
Vi fikk warning om at vi prøvde å sende en bolsk verdi når man forventet en ikke-bolsk verdi i styled component. Dette kan unngås ved å bruke `$` foran navnet slik at props som er ment for styled components ikke rendres til DOM elementet, les [HER](https://styled-components.com/docs/api#transient-props).
Nå kunne hele variabelen slettes fordi det var en styled component uten noe styling 😎
> Fjerne warning om non-string props

- package.json
For å slippe å hoppe mellom rot og `./backend`
> 🧑‍💻 start:dev-preprod skal kunne kjøres fra rotmappa

- src/frontend/Sider/Behandling/Brev/Delmal.tsx
- src/frontend/Sider/Behandling/Brev/DelmalMeny.tsx
- src/frontend/Sider/Behandling/Brev/Sanity/ValgfeltSerializer.tsx
- src/frontend/Sider/Behandling/Brev/Sanity/queries.ts
- src/frontend/Sider/Behandling/Brev/Valgfelt.tsx
- src/frontend/Sider/Behandling/Brev/typer.ts
Når man velger et valgfelt skal endringen komme med i den genererte brevteksten.
Denne PRen fikser delvis generering av valgtfelt. Når saksbehandler tar et valg skal dette reflekteres i den genererte brevteksten. 
**Hva funker?**
✅ Valgfelt som bare har `Tekst` uten variabler
**Hva mangler?**
🚫 Variabler i `Tekst`
🚫 Fritekstvalg
**Før valg:**
**Etter valg:**
> 🚧  Preview av Tekst i valgfelt

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/AktivitetSelect.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/AntallDagerSelect.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/PeriodetypeSelect.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/UtgiftsperiodeValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/VelgBarn.tsx
- src/frontend/Sider/Behandling/vilkår.ts
- src/frontend/komponenter/Skjema/TextField.tsx
- src/frontend/utils/dato.ts
- src/frontend/utils/tall.ts
Legge inn resterende felter (barn og utgifter):
Se commit for commit
- Frem til vi vet hvordan designet skal se ut er det gjort en enkel visning av barn med checkbokser
- Utgifter er kun et rent tekstfelt. Det gjøres om til en tallverdi dersom det er mulig. Det er lagt inn på TODO kort på trello å se på dette. 
- Må kunne håndtere en dato-streng som er tom ("")
- Gjør om antall dager med aktivitet og pass til `number`
- `index` -> `indeks`
- Sette property i `UtgiftsperiodeValg` slik at hver komponent ikke trenger å ta hensyn til hvilken property i skjema den er.
> Beregning utgifter

- src/frontend/Sider/Behandling/Brev/Delmal.tsx
- src/frontend/Sider/Behandling/Brev/DelmalMeny.tsx
- src/frontend/Sider/Behandling/Brev/Sanity/ValgfeltSerializer.tsx
- src/frontend/Sider/Behandling/Brev/Tekst.tsx
- src/frontend/Sider/Behandling/Brev/Valgfelt.tsx
Når saksbehandler fyller ut variabler i brevmenyen skal disse komme med i den genererte brevteksten ✍️ 
Denne PRen fikser variabler i `Tekst`-komponentene. Variabler ytterst i delmalen tas i neste PR. Visualisering av hva som er gjort foreløpig:
Ps. Ser at variablene i brevmenyen ikke nødvendigvis følger rekkefølgen de er definert i i brevmalen. Mulig vi må endre på spørringene for å fikse dette 💭
> 🚧 Variabler i valgfelt

- src/frontend/Sider/Behandling/Brev/Delmal.tsx
- src/frontend/Sider/Behandling/Brev/DelmalMeny.tsx
- src/frontend/Sider/Behandling/Brev/Sanity/ValgfeltSerializer.tsx
- src/frontend/Sider/Behandling/Brev/Sanity/queries.ts
- src/frontend/Sider/Behandling/Brev/Valgfelt.tsx
- src/frontend/Sider/Behandling/Brev/VariabelSerializer.tsx
- src/frontend/Sider/Behandling/Brev/Variabler.tsx
- src/frontend/Sider/Behandling/Brev/typer.ts
Variabler definert i delmal skal vises i brevmenyen og tas med i det genererte brevet.
> ✨  Variabler i delmal

- .nais/dev.yaml
- .nais/prod.yaml
- src/backend/auth/attachToken.ts
- src/backend/server.ts
- src/frontend/App.tsx
- src/frontend/context/AppContext.ts
- src/frontend/utils/fetch.ts
…ikke har gyldig token
Frontend viser info om at man må laste om siden hvis et kall returnerer 401
For å enklere kunne få en oppdatert sesjon ved utdatert token.
Dette skjer oftere i frontend då vi ikke håndterer refreshtokens lokalt, men i dev/prod håndterer wonderwall refreshtoken
Kan testes med:
* Logg inn
* Opprett en behandling
* Fjern cookie for sessjonen, `tilleggsstonad-local` lokalt og `io.nais.wonderwall.session` i dev
* Velg fane `Vilkår for aktivitet`
* Gå tilbake til første fanen
> Redirect 401 login

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Stønadsperiode/StønadsperiodeValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/vedtaksvalidering.ts
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/utils.ts
- src/frontend/komponenter/Skjema/DateInput.tsx
- src/frontend/typer/vedtak.ts
Lage felter som trengs for å beregne og gjøre vedtak. 
Målet er å splitte eksisterende felter (tatt fra EF) opp i en gruppe med felter for stønadsperiode og en gruppe med utgifter. 
Foreløpig ser det sånn her ut, men kun feltene under "perioder for stønad" skal faktisk være sånn:
> 🚧 Lage felter for stønadsperiode

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/Utgifter.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/vedtaksvalidering.ts
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/utils.ts
- src/frontend/hooks/felles/useFormState.ts
- src/frontend/hooks/felles/useRecordState.ts
- src/frontend/typer/vedtak.ts
Legger inn felter for å registrere utgifter per barn i behandling. 
**Hva er gjort:** 
- Lagt til felter. Skal være år måned på utgift, men har foreløpig bare brukt dato fordi de input-feltene var alt laget med leservisning så det gikk raskere. 
- Endret formstate slik at den håndterer states av records.
- Initialiserer hvert barn med 1 tom utgiftsrad. 
- Alt er lister, men foreløpig kan man bare registrere 1 utgift likevel. 
**Uvissheter:**
- Usikker på om barn skal initialiseres med 1 tom rad eller vise knapp for å "legge til en ny". Enkelt å bytte, men det gjøres i såfall når mulighet for å legge til flere utgifter kommer fordi samme logikk brukes for å legge til ny.
- Valideringen må gås opp
- Mange spørsmål om barn og hvilke barn som skal med osv, foreløpig er dette hardkodet og må …
> 🚧 Felter for utgifter

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Beregningsresultat.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeVedtak.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Stønadsperiode/StønadsperiodeValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/vedtaksvalidering.ts
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/utils.ts
- src/frontend/typer/vedtak.ts
- src/frontend/utils/dato.ts
Kun fokus på funksjonalitet: Skal kunne sende inn data og få tilbake beregningsresultat. 
Må diskuteres: 
- Skal vi beregne månedsbeløpet i backend? Burde også rundes av for å ikke få spørsmål fra SB?
**Les commit for commit** (Er en key i map som blir lagt på utenfor)
> ✨ Funksjonalitet for beregning av stønad 

- src/frontend/Sider/Behandling/BehandlingInnhold.tsx
- src/frontend/Sider/Behandling/Brev/VelgBrevmal.tsx
- src/frontend/Sider/Behandling/Høyremeny/Høyremeny.tsx
Håndterer ikke åpen/lukket høyremeny
Har ikke tatt inn allt av flex-properties på `BehandlingContainer`, `InnholdWrapper` eller `HøyreMenyWrapper`
https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16160
> Høyremeny for å kunne vise totrinnskontroll

- src/frontend/Sider/Behandling/Totrinnskontroll/Totrinnskontroll.tsx
- src/frontend/Sider/Behandling/Totrinnskontroll/TotrinnskontrollUnderkjent.tsx
Visning av at et vedtak er underkjent. Tenker styling kan fikses på senere.
Kan testes med
```typescript
const hentTotrinnskontroll = useCallback(
(behandlingId: string) => {
settTotrinnskontroll(
byggRessursSuksess({
status: TotrinnskontrollStatus.TOTRINNSKONTROLL_UNDERKJENT,
totrinnskontroll: {
opprettetTid: '2023-01-01T01:01:01',
opprettetAv: 'Sara Eirik',
årsakerUnderkjent: [ÅrsakUnderkjent.VEDTAKSBREV],
begrunnelse:
'en god begrunnelse som går over flere rader kanskje? Idag er det fredag',
},
})
);
},
[request, settTotrinnskontroll]
);
```
Det ble fikset med å bruke inline på alert
Store forskjellen:
I EF har man dette for visning av ikone og tekst. Denne ikonen har bakgrunnsfarge. 
```typescript
<div className="ikon-med-tekst">
<Info height={20} width={20} /> …
```
> Visning av underkjent totrinnskontroll

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeVedtak.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/Utgifter.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/utils.ts
- src/frontend/Sider/Behandling/vilkår.ts
Til nå har barn vært mocket i vedtak og beregning, som har gjort at kallet feiler. Nå henter man barnene fra grunnlagsdata i vilkårsvurdering, og lagring av vedtak fungerer 🥳 
For å få det til måtte kallet for å hente vilkår endres så det til med barnId (UUID). Se [PR 73](https://github.com/navikt/tilleggsstonader-sak/pull/73)
> Lagre vedtak ved bruk av ekte barn

- src/frontend/Sider/Behandling/Totrinnskontroll/FatteVedtak.tsx
- src/frontend/Sider/Behandling/Totrinnskontroll/SendtTilBeslutter.tsx
- src/frontend/Sider/Behandling/Totrinnskontroll/Totrinnskontroll.tsx
- src/frontend/hooks/useHentTotrinnskontroll.ts
Flyttet ut visning at den er sendt til beslutter i egen oppgave, backend må jeg kanskje vente litt med.
https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16831
Kan testes med
```typescript
settTotrinnskontroll(
byggRessursSuksess({
status: TotrinnskontrollStatus.IKKE_AUTORISERT,
totrinnskontroll: { opprettetTid: '2023-01-01T13:10:13', opprettetAv: 'Meg' },
})
);
```
`TotrinnskontrollStatus`-enum kan endres senere når backend kommit lengre
> Totrinnskontroll - visning at behandling er Sendt til beslutter

- src/frontend/Sider/Oppgavebenk/typer/enhet.ts
Skal ikke bruke enheten for Enslig i TS
> Oppdatert til riktig Nasjonal kø for NAY

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/Sider/Behandling/Fanemeny/Fanemeny.tsx
- src/frontend/Sider/Behandling/Fanemeny/faner.tsx
- src/frontend/Sider/Behandling/Totrinnskontroll/SendTilBeslutterFooter.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16071
Denne mangler litt styling, tenker vi får fikse det med 2 flex-columns i egen PR (høyremenyn dekker ikke 100% av høyden)
Det blir også litt krøll med at pagineringen av brevet går inn i SendTilBeslutter
Se screenshots
> Skal kunne sende behandling til beslutter

- src/frontend/Sider/Behandling/Totrinnskontroll/FatteVedtak.tsx
- src/frontend/Sider/Behandling/Totrinnskontroll/SendtTilBeslutter.tsx
- src/frontend/Sider/Behandling/Totrinnskontroll/Totrinnskontroll.tsx
- src/frontend/context/BehandlingContext.ts
- src/frontend/hooks/useHentTotrinnskontroll.ts
- src/frontend/hooks/usePrevious.ts
- src/frontend/typer/behandling/behandlingStatus.ts
Div endringer for å få totrinnskontroll til å virke. Har delt opp commits, den siste er den største
Har valgt å ikke flytte send til beslutter i denne PR, men at det gjøres i en egen oppgave. Det er både backend og frontend som skal til for at den skal virke.
[Skal oppdatere behandlingErRedigerbar](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/e309ceab6514e504629061f675b3b3bcc33553f6)
[Post for å angre send til beslutter](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/384f97bf5583dc6c92ce10e69514afda1b383480)
[Når man godkjenner så skal man fortsatt vise modalen, men ikke vise n…](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/3bb0b19b4441c4c69995c5a90bee6f2d2ffb72b1) 
[Når man fatter vedtak skal man trigge henting av behandling på nytt, …
> Fikset totrinnskontroll med flyt og state

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Stønadsperiode/StønadsperiodeValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/Utgifter.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/vedtaksvalidering.ts
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/utils.ts
- src/frontend/typer/vedtak.ts
Det er nødvendig å kunne legge til flere rader for både [stønadsperiode](https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16143) og [utgifter per barn](https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16144) 
**Se commit for commit (om du vil men er litt smooth)**
Burde `RecordState` som ble laget tidligere for å håndtere utgifter endres fra å være en egen greie til å bare være `Record<ListState<Utgift>>`. Usikker på hvordan dette vil være i praksis, men det er kanskje litt smudere å ha en egen state per liste og ikke en stor, men så lagres statene i formen i en record. 
Nå er hele `Record<string, Utgift[]>` en egendefinert formstate-greie. Spesielt ved sletting av element i lista ser dette litt corny ut. …
> ✨ Flere rader for stønadsperiode og utgifter i vedtak og beregning

- src/frontend/Sider/Behandling/Totrinnskontroll/FatteVedtak.tsx
`frontendFeilmeldingUtenFeilkode` var feil felt :-)
> Totrinn -> fatter vedtak skal vise feilmelding hvis det feiler

- src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingOversikt.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx
- src/frontend/hooks/useFagsakPerson.ts
Behandlingsoversikten har til nå bare vært mocket, men nå hentes alle fagsaker med behandlinger fra API. 
Må merges etter [PR 96](https://github.com/navikt/tilleggsstonader-sak/pull/96) i ts-sak
> ✨ Vise frem behandlinger i behandlingsoversikt

- src/frontend/Sider/Behandling/Brev/Html.tsx
Brev skal signerer av saksbehandler og beslutter. Legger derfor inn placeholdere i html'en, så backend kan legge på signaturene.
Må se på spacing/styling i avslutningen siden 🤠 
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16779)
**Brev med signatur** 📷
> ✨ Brevhtml skal ha placeholder for signatur for saksbehandler og beslutter

- src/frontend/App.tsx
- src/frontend/komponenter/PersonSøk.tsx
Ønsker å kunne [søke opp personer i systemet](https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16841) slik at det er mulig å finne brukere uten å gå via databasen. 
- Man kan søke på både fnr og ekstern fagsakid
- Ved suksess redirectes man rett til personens side
- Ved feil vises en popover med feilmelding
Feil ved søk på fnr som ikke har fagsak: 
Feil ved søk på ekstern fagsakid:
> Søke opp fnr og ekstern fagsakid

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/Sider/Behandling/Brev/BrevLesevisning.tsx
Når en behandling er sendt til beslutter, eller ferdigstilt skal det lagrede brevet vises.
> ✨ Skal hente lagret brev når behandling ikke er redigerbar

- src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx
Har lagt inn en knapp for å henlegge behandling via behandlingsoversikt. Har ikke lagt til noe mer funksjonalitet enn at den blir henlagt med årsak `FEILREGISTRERT` og det skjer ikke noe etterpå (ikke refresh eller visning av feilmelding). Nå får vi testet at henlegging fungerer og kan bruke det for testing. Knappen vises også uansett status
> ✨ Skal kunne henlegge behandling

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
* Table må ha en row for å validere riktig html
* Skal ikke vise feilmelding/validere stønadsperioder når man henter målgrupper og aktiviteter, men ikke har noen stønadsperioder ennå
> Fikset warnings koblet til målgruppe og aktivitet

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/Sider/Behandling/Brev/useBrev.ts
Frittstående brev fungerer ikke atm fordi `useBrev` brukes både i frittstående brev og vedtaksbrev. Frittstående brev ligger utenfor contexten til en behandling og `useBehandlig()` kan derfor ikke kalles fra `useBrev()`. Behandling bør heller sendes inn så den er tilgjengelig. 
Siden frittstående brev ikke er knyttet til en behandling har den heller ingen `behandlingId` så det er lagt til sjekk for om denne er `undefined` slik at det ikke kastes feil ved initialisering av brevmottaker.
> 🐛 Behandling må sendes inn til useBrev

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/LeggTilAktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/LeggTilMålgruppe.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx
Det er ikke gyldig å sette dato til undefined, men hvis man fjerner dato så blir feilmeldingen ståendes og ikke viser 
* Setter tom < fom 
*  -> viser feilmelding om tom < fom
* Fjerner fom
* -> viser fortsatt feilmelding om tom < fom fordi fom egentlige ikke blir fjernet fra statet
https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-17406
> Skal kunne resette datoer i perioder

- src/frontend/Sider/Behandling/Inngangsvilkår/typer.ts
- src/frontend/Sider/Behandling/Vilkårvurdering/tekster.ts
Vise frem målgrupper og aktiviter som ble lagt til i [PR 122 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/122) som valg i inngangsvilkårene. 
PS: Vi har ikke laget noe mapping for penere navn i dropdown. Det kan legges inn når siden skal styles
> Legg til flere målgrupper og aktiviteter i inngangsvilkår

- src/frontend/App.tsx
- src/frontend/Sider/Behandling/Brev/useBrev.ts
- src/frontend/Sider/Behandling/Brev/useMellomlagrignBrev.ts
- src/frontend/Sider/Behandling/Brev/useMellomlagringFrittståendeBrev.ts
- src/frontend/Sider/Behandling/Totrinnskontroll/FatteVedtak.tsx
- src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrev.tsx
- src/frontend/context/AppContext.ts
- src/frontend/komponenter/Toast.tsx
- src/frontend/typer/toast.ts
Gjøre det mulig å gi feedback til bruker ved kall til backend. 
Tatt i bruk for å gi beskjed om at frittstående brev er sendt til bruker.
> ✨ Legg til toast som en state i AppContext

- src/frontend/Sider/Behandling/Brev/Variabler.tsx
Skal ikke vise html-variabler i brevmeny, kun i generert brev ([favro](https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-17363&secret=WJKlDZ3sr_1ysJBnmrdKLkanApcz-OOZlzcZkuS4pQb))
Før: 
Etter:
> Skjul variabler som er html-felter fra brevmeny

- src/frontend/App.tsx
Det er sykt smud 👍 
PS: `as="h1"` gjør at det ble en tekst og ikke en knapp, så den måtte fjernes
> 💄 Skal sendes til oppgavebenk ved trykk på ts i header

- src/frontend/Sider/Oppgavebenk/filter/Oppgavefiltrering.tsx
- src/frontend/Sider/Oppgavebenk/typer/oppgave.ts
Eksisterende kode gjenbrukte bare behandlingstema og behandlingstype som var brukt hos EF. Oppgavesystemet har eget kodeverk som definerer hvilke behandlingstemaer og behandlingstyper som er gyldige for et gitt tema (OBS: tema != behandlingstema)
Legger her til behandlingstema og behandlingstyper som er gyldige for temaene TSO og TSR, ref: https://github.com/navikt/oppgave/blob/faaf9374fa94c32f70ff47acdfe64526fe000bcf/src/main/resources/data/gjelder.json#L4
Betydning av kodene er hentet fra https://kodeverk-web.dev.intern.nav.no/
> 🚧 Ta i bruk behandlingstema og behandlingstype som er gyldige for TSO og TSR

- src/frontend/Sider/Behandling/BehandlingInnhold.tsx
- src/frontend/Sider/Behandling/Fanemeny/Fanemeny.tsx
- src/frontend/Sider/Personoversikt/Personoversikt.tsx
- src/frontend/komponenter/PersonHeader/PersonHeader.tsx
Enkelt kunne se navn og kopiere fnr
PS: Har brukt `CopyButton` som er beta. Siden jeg først hadde beta i filen så testet jeg ut `HStack` også 🤠.
PSS: Prøvde å ta i bruk spacing fra aksel. 1 hos aksel = 4px, dvs. at  f.eks. `ASpacing4 = 1rem`
> ✨ Legg til personHeader med navn og personident

- src/frontend/Sider/Personoversikt/Dokumentoversikt/DokumentRad.tsx
- src/frontend/Sider/Personoversikt/Dokumentoversikt/Dokumentoversikt.tsx
- src/frontend/Sider/Personoversikt/PersonoversiktInnhold.tsx
- src/frontend/typer/dokument.tsx
Skal kunne se alle dokumentene som hører til en bruker.
Hører sammen med: 
- [PR 57](https://github.com/navikt/tilleggsstonader-integrasjoner/pull/57) i integrasjoner
- [PR 143](https://github.com/navikt/tilleggsstonader-sak/pull/143) i sak
Valgte `zebraStripes`, derfor er øverste raden grå. Mulig det ikke ser så bra ut med få rader, men mer oversiktlig om det er flere rader
> Dokumentoversikt

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Medlemskap.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/utils.ts
Gikk litt fort i svingene på #163 så verdi fra vilkårsvurdering ble sendt inn som `e.target.value` men det skulle bare vært `e`. Og `svarJaMapping` ble brukt både for ja og nei 🤠
> 🐛 Endre målgruppe, skal kunne endre svar på medlemskap-radio

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/hooks/felles/useFormState.ts
- src/frontend/utils/periode.ts
Backend gjør mye validering av målgruppe når det sendes inn, men for å fange de verste feilene er det lagt inn validering av perioden (fom <= tom osv). 
Validering av begrunnelse på vilkårsvurdering bør legges til når det er bestemt når det er påkrevd og ikke.
Som alltid er ikke feilvisning på felter i tabell det fineste, men hvertfall alignet alle felter på topp:
> ✨ Målgruppe - valider periode

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeInnhold.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/validering.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts
- src/frontend/komponenter/Ikoner/Vilkårsresultat/VilkårsresultatIkon.tsx
Hadde brukt `VilkårResultat` i stedet for å lage eget enum for `VilkårperiodeResultat`.
Største forskjellen er `IKKE_TATT_STILLING_TIL` = `IKKE_VURDERT` og `SLETTET` fantes ikke.
Oppdaterte komponenten for statussymbol så begge kan sendes inn og alt ser likt ut
> 🐛 VilkårperiodeResultat != VilkårResultat

- src/frontend/Sider/Behandling/BehandlingContainer.tsx
- src/frontend/Sider/Behandling/BehandlingInnhold.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/BarnDetaljer.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Oppsummering.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Visningskomponenter.tsx
- src/frontend/Sider/Behandling/Venstremeny/Venstremeny.tsx
- src/frontend/typer/behandling/behandlingFakta/behandlingFakta.ts
- src/frontend/typer/behandling/behandlingFakta/faktaAktivitet.ts
- src/frontend/typer/behandling/behandlingFakta/faktaBarn.ts
- src/frontend/typer/behandling/behandlingFakta/faktaHovedytelse.ts
- src/frontend/typer/common.ts
Saksbehandler skal se en oppsummering av fakta som tilhører en behandling i venstremeny. 
OBS: har lagt fanene i en liste for skal komme historikk senere
Aktivitet mappes kun ut med "utdanning" dersom bruker er registrert med dette, fordi søknaden ikke tar inn noe annet enn dette nå. Må oppdateres til å mappe om når søknaden oppdateres. Bør vurdere mapping i backend
> ✨ Oppsummering av fakta i venstre meny

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/aktivitet.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/målgruppe.ts
- src/frontend/komponenter/Skjema/Select.tsx
- src/frontend/komponenter/Skjema/SelectMedOptions.tsx
Aktivitet- og målgruppetype skal velges både i vilkårsperioder og i stønadsperioder. Lagde derfor en egen komponent som tar inn valg som mappes ut i en select. Denne kunne brukes for å slippe `typeSelect` som tidligere ble sendt til `EndreVilkårsperiodeRad`
> ♻️ Flytt valg av type til felles komponent

- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/KildeIkon.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/SlettVilkårperiodeModal.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeRad.tsx
- Knapper i tabell skal være `xsmall`
- Ikon skal brukes for å vise kilde (ikke tekst)
- Sletting av vilkårsperioder kan ikke trigge rerun av hentVilkårsperioder om vi ikke oppdaterer state i context. Fordi vi ikke har kontroll på redigering på tvers av målgrupper/aktivitet bør disse oppdatere state i context direkte og ikke hente alt på nytt. 
- Eksisterende bug var at man ikke så at en periode var slettet med mindre man refreshet siden 
_Les commit for commit_
> 🐛 Småfix i vilkårperiode

- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Aksjonsknapper.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/validering.ts
- src/frontend/context/InngangsvilkårContext.ts
- src/frontend/hooks/felles/useFormState.ts
- src/frontend/komponenter/Skjema/DateInput.tsx
- src/frontend/utils/dato.ts
- src/frontend/utils/periode.ts
Hvordan stønadsperioder ser ut varierer basert på hvilken state man er i: 
- Ikke redigering (lik visning for beslutter minus knapper)
- [1] Det finnes ingen stønadsperioder
-  Man ser kun en knapp med "Legg til stønadsperioder". Ved trykk på denne legges det til en tom rad og redigeringsmodus aktiveres
- [2] Det finnes stønadsperioder
-  Stønadsperioder vises i lesemodus (kun verdier)
- Redigering
- [3] Stønadsperioder finnes
- Alle verdier kan redigeres (alle rader samtidig)
- Man kan slette og legge til rader 
- [4] Ingen stønadsperioder finnes 
- Knapp for å legge til ny vises (dette skjer kun om man sletter alle eksisterende perioder)
- Det er nå mulig å slette alle rader
- Man legger til rader i bunnen hver gang
- Knapp for å si "ingen gyldige stønadsperioder". Trenger vi egentlig …
> ✨ ♻️ Stønadsperioder - nytt design med tilhørende funksjonalitet

- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Stønadsperiode/StønadsperiodeValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
- src/frontend/komponenter/Skjema/DateInput.tsx
- src/frontend/komponenter/Skjema/DateInputMedLeservisning.tsx
Lag egen komponent som sørger for at datofelt rendres på nytt ved switch mellom leservisning og redigering av dato. Dette gjøres for å håndtere at innsendt verdi kan være annerledes og vil trigge en ny rendring av `defaultValue`.
Alternativet er å bruke `setSelected` hver gang input endrer seg, men det blir en liten loop :(
> Datoinput skill ut leservisning

- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts
- Bruke enumTilTekst for å slippe capslock på alle typer
- Wrappe tekst i tabell med `<BodyShort small>` så teksten når man har redigering med leservisning er lik teksten for kun visning. 
Før: 
Etter:
Må fortsatt finne en løsning for at "slettet" ikonet tar mye mer plass enn resten
> 💄 Tekst i vilkårperiodetabeller

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeVilkår.tsx
Uføretrygd gis på samme måte som omstillingsstønad, så dersom de er vurdert etter andre ledd i uføreparagrafen oppfyller de ikke vårt vilkår for medlemskap.
Hører sammen med [PR 180 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/180)
> Skal spørre hvilket ledd uføretryd er vurdert etter for å vurdere medlemskap

- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/validering.ts
Backend skal være ansvarlig for validering på tvers av vilkårsperioder og stønadsperioder
> 🗑️  Fjern (noe) validering stønadsperioder

- src/frontend/Sider/Behandling/BehandlingInnhold.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
Man skal kunne navigere i bunnen av inngangsvilkår.
Håndterer ikke sjekk om ting er lagret. 
"Fortsett senere" betyr egt bare "gå ut av behandlingsvinduet", men senere burde det kanskje være "sett på vent" inkludert
> ✨ Skal kunne navigere til neste steg i bunnen av inngangsvilkår

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeVilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts
- src/frontend/Sider/Behandling/Vilkårvurdering/JaNeiVurdering.tsx
Ref [skissene](https://www.figma.com/file/T5lYk3vCOWiahrAs3jIaby/TILDE-~--TS-saksbehandling-pass-av-barn?type=design&node-id=3049-9889&mode=design&t=Y23J3J6XK2EWSk2N-4) er begrunnelse obligatorisk dersom medlemskap ikke oppfylt.
Validering av begrunnelse kommer i annen PR.
> ✨ Skal vise om begrunnelse er obligatorisk eller ikke ved vurdering av medlemskap

- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Oppsummering.tsx
- src/frontend/typer/behandling/behandlingFakta/faktaHovedytelse.ts
Liten quickfix på at fikse at man får flere ytelser. M sa at hon hade skisser som var sånn her et sted, med komma. Tenker det er greit nå. Senere trenger vi mapping til tekst.
Koblet til/se beskrivelse
* https://github.com/navikt/tilleggsstonader-sak/pull/194
> Man får nå en liste med hovedytelser

- src/frontend/Sider/Behandling/Brev/Sanity/ValgfeltSerializer.tsx
Block content blir pr. default wrappet i en p-tagger av `<PortableText />`, som medfører litt margin over og under. Valgfelt skal kunne brukes uten spacing mellom nye linjer, etter ønske fra Hilde (De to første setningene i brevet under skal ikke ha spacing mellom). 
**Før**
**Etter**
> 🐛 Fjern spacing/margin mellom valgfelt i brev

- src/frontend/Sider/Behandling/Brev/DelmalMeny.tsx
- src/frontend/Sider/Behandling/Brev/Valgfelt.tsx
Så man faktisk ser hvilke valg som er tatt tidligere. Den mellomlagrede verdien ble brukt i brevgenereringen, men ikke vist i brevmenyen.
**Før**
**Etter**
> 🐛 Skal bruke verdi fra mellomlager i select for valgfelt

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
Likt statet
`const [aktivFane, settAktivFane] = useState<string>(path || FanePath.INNGANGSVILKÅR);`
Hvis ikke får man en tom side når man klikker på noe som lenker til behandlingen :-)
> Skal sette aktiv fane til Inngangsvilkår som default

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
- src/frontend/Sider/Behandling/Venstremeny/Venstremeny.tsx
* Endret tabs i VenstreMenyn til å være sticky, og ikke hele venstremenyn
* Tablist for behandling skal være sticky, for å kunne navigere uten å scrolle opp når man eks scrolled ned på siden på pass av barn
For at venstremenyn skal ha en border-right som dekker hele siden så er `min-height: calc(100vh - 97px);` lagt til.
Bygger videre på 
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/232
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-18559
https://github.com/navikt/tilleggsstonader-sak-frontend/assets/937168/591523ac-f070-4956-82aa-4e47f2216dc2
https://github.com/navikt/tilleggsstonader-sak-frontend/assets/937168/67806fba-78fa-416a-b59d-6eb2864becb9
https://github.com/navikt/tilleggsstonader-sak-frontend/assets/937168/e004dded-187 …
> Fikset deler som prøvde å være sticky, og burde være sticky

- src/frontend/komponenter/PersonSøk.tsx
Det er ønskelig å kunne opprette en fagsak-person for å få se personoversikten på en person, hvis personen finnes i Arena
Dette som en del av å hente tiltak på en person
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-19957
* Tekst er ikke avklart, og kan endres senere
Koblet til
* https://github.com/navikt/tilleggsstonader-sak/pull/240
Hvis personen finnes i Arena får man valget å opprette fagsak-person og blir videresendt til personoversikten
> Opprett fagsakPerson hvis personen finnes i Arena

- src/frontend/Sider/Behandling/Brev/Sanity/queries.ts
- src/frontend/Sider/Behandling/Brev/useBrev.ts
Etter [endring av hvordan man refererer til variabler i sanity ](https://github.com/navikt/tilleggsstonader-brev-sanity/pull/15) måtte spørringen for malstruktur oppdateres. Variabler ligger ikke lenger direkte som en referanse, men som et objekt som inneholder en referanse. 
Siden denne oppdateringen i sanity førte til at alle variabelreferanser ble ugyldige ble det derfor slettet mange brev. Har derfor lagt inn en liten sjekk på at brevmal faktisk ble funnet i sanity før man setter strukturen. Slik at ikke hele løsningen kræsjer om et mellomlagret brev blir slettet før man jobber videre
> 🐛 Hent variabler med ny struktur i sanity og håndter at brev er slettet siden forrige mellomlagring

- src/frontend/Sider/Behandling/Brev/DelmalMeny.tsx
- src/frontend/Sider/Behandling/Brev/brevUtils.ts
Forsøkte tidligere å bare ta _id fra valg, men fritekst har ikke _id og ble derfor feil.
> 🐛  Skal kunne velge fritekst som valg i valgtfelt

- src/frontend/Sider/Behandling/Brev/brevUtils.ts
Valg kan være undefined som gjør at sjekken lagt til i #247 knekker brevsiden ved innlasting fordi bruker ikke har valgt et felt i valgfeltet 😢
> 🐛 Håndter at valgfelt kan være undefined

- src/frontend/Sider/Journalføring/Standard/AvsenderPanel.tsx
- src/frontend/Sider/Journalføring/Standard/Journalføring.tsx
- src/frontend/hooks/useJournalføringState.ts
Skal vise panel med informasjon om avsender på journalføringssiden. Dersom avsender er satt skal panelet ikke være redigerbart. Dersom avsender ikke er satt skal saksbehandler kunne skrive inn navn på avsender selv, eller huke av for at avsender er bruker.
Avsender satt fra før:
Avsender ikke satt fra før:
> skal vise panel med informasjon om avsender i journalføringsbildet

- README.md
- src/frontend/Sider/Behandling/Vilkårvurdering/Begrunnelse.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/EndreDelvilkår.tsx
Gikk for `disabled` framfor `readOnly`, fordi førstnevnte ikke lar seg fokusere med tastatur.
> Deaktivert begrunnelse når vilkårsverdi ikke er valgt

- src/frontend/Sider/Behandling/Brev/Fritekst.tsx
- src/frontend/Sider/Behandling/Brev/Variabler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiodeInnhold.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/JaNeiVurdering.tsx
- src/frontend/Sider/Journalføring/Standard/AvsenderPanel.tsx
- src/frontend/komponenter/Skjema/TextField.tsx
- src/frontend/utils/utils.ts
Se commit per commit 
* [Skal ikke ha autocomplete på TextField](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/49a92720c1966deb2a1afa39865b624fd546dccc)
* [Skal sende med begrunnelse for å få den TextArea til å bli controlled](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/afbe1935663fb46982c46966877e32554197f983)
* [Textareas må ha defaultverdi for å være controlled](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/c493d6a5056dda6d58976235ad505cf8df1f7bcf)
* [Endrer utgift til heltall. Fjerner spaces i tilfelle man kopierer inn…](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/fa23ca1937cfb7fe20574a615755567b8b745741)
> 💄🐛 Div småfiks i saksbehandlingen

- src/frontend/Sider/Behandling/Brev/Sanity/queries.ts
Variabler i valgtfelt funker ikke uten dette.
> 🐛  Skal også derefe referanser/variabler i valgtfelt

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
Når den er en egen state og bruker useEffect så endres aktivFane en redering etter at man har endret steg - i tilfelle når man går fra inngangsvilkår til stønadsvilkår
Ser ingen god grunn til at det skal være en egen state som oppdateres samtidig som man bruker navigate. 
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20321
Denne henger sammen med alle andre PR's koblet til stegflyt.
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/270
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/271
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/272
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/273
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/274
* …
> Stegflyt 1 - AktivFane trenger ikke å være en egen state.

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
- src/frontend/Sider/Behandling/faner.tsx
- src/frontend/context/StegContext.ts
- src/frontend/typer/behandling/steg.ts
Hvis man går inn på brevfanen når den er låst, med URL eller klikker, så renderes brevsiden og feiler beroende på state. 
Gjennom å ikke rendere komponentene hvis behandlingen er i feil state hentes ikke data i unødvendige tilfeller og man unngår ev. feil. 
Flytter låsing av tabs til hentBehandlingfaner for å ha det på et sted.
Låser vedtakssiden og brev hvis behandlingen er på et steg før disse - då man ikke burde endre på hverken vedtaket eller brev(?).
❗ Denne delen kan diskuteres om den skal være med/fjernes. 
Denne henger sammen med alle andre PR's koblet til stegflyt.
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/270
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/271
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/272
* …
> Stegflyt 2 - Fjerner rendering av tabs hvis fanen er låst

- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
- src/frontend/Sider/Behandling/Stønadsvilkår/Stønadsvilkår.tsx
- src/frontend/komponenter/Stegflyt/StegKnapp.tsx
Idag vises "Rediger steg" på eks "Tilsyn Barn"-siden, når man er i inngangsvilkår. Klikker man på den så får man opp
> Kunne ikke redigere steg: Ukjent feil. Feilkode: ff5c5a65-bb2d-4132-ad91-79f756b3da97
Se commit for commit
* [Endrer navn på NesteStegKnapp til StegKnapp då den håndterer redigeri…](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/88db9efc4084ba869543f0fb0c33bcd9ec9d961b)
* [Lar StegKnapp håndtere om den skal vises eller ikke](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/d44fa21b3541b7c54e22d0c37e095718863971c1)
* [Skal kun vise rediger steg hvis steget på behandlingen er etter stege…](https://github.com/navikt/tilleggsstonader-sak-frontend/commit/be2d1deb231cb38e7ed0d968a8e42f7ff9a756f1)
Denne henger sammen med alle andre PR's koblet til …
> Stegflyt 3 - Forbedrer stegknapp

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Felles/SelectVedtaksresultat.tsx
- src/frontend/komponenter/Stegflyt/StegKnapp.tsx
…dtak
Vedtaksiden er ikke påkoblet stegflytet.
Jeg tenker det er fint hvis vi bruker den samme type logikken som vi har på de 2 første stegene. 
Her brukes `StegKnapp` med egen metode for å kunne sende med en egen lagringsmetode til den. 
Denne fikser 2 av punktene i https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20313
Denne henger sammen med alle andre PR's koblet til stegflyt.
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/270
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/271
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/272
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/273
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/274
* …
> Stegflyt 4- Stegflyt vedtak og beregning

- src/frontend/Sider/Behandling/faner.tsx
Burde ikke vise brevfanen hvis behandlingen er henlagt, då det vanligvis ikke finnes noe brev i et slik tilfelle.
Før:
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20317
Denne henger sammen med alle andre PR's koblet til stegflyt.
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/270
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/271
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/272
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/273
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/274
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/275
> Stegflyt 6 - Skjul brev-fane hvis henlagt

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeVilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/målgruppe.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts
- src/frontend/Sider/Behandling/Vilkårvurdering/JaNeiVurdering.tsx
Alle "målgrupper" som går under `NEDSATT_ARBEIDSEVNE` må ha en vurdering av om utgiftene dekkes av annet regelverk, som gir oppfylt hvis svaret er NEI. Begrunnelse kreves hvis svaret er JA. 
Switch ble kaotisk når det kom flere vilkår, så gikk for if i stedet. 
Henger sammen med [PR 267 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/267)
**OBS**
Det vi nå kaller målgruppe burde bytte navn til noe annet (f.eks. hovedytelse eller liknende). Målgruppe er egentlig nedsatt arbeidsevne, enslig eller gjenlevende, men dette er mye jobb så må vente. `FaktiskMålgruppe` brukes i frontend for det som er `Målgruppe`
> Vilkår dekkes av annet regelverk

- src/frontend/Sider/Behandling/BehandlingInnhold.tsx
- src/frontend/Sider/Behandling/Høyremeny/Høyremeny.tsx
- src/frontend/Sider/Behandling/Venstremeny/Venstremeny.tsx
Vi har kun hatt høyremenyen i løsningen fordi det var plasseringen til totrinnskontrollen. Denne er nå flyttet over tabs i venstermenyen så alt innholdet kan få litt mer plass. 
For beslutter: 
For saksbehandler: 
Underkjent: 
Før sendt til beslutter (ser bare oppsummering som før):
> 💄 Fjern høyremeny og plasser totrinnskontroll over venstremeny

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/AktivitetVilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeVilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/SlettVilkårperiodeModal.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/DelvilkårDetaljer.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/OppsummertVilkårsvurdering.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/VilkårperiodeKortBase.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/tekstmapping.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts
- src/frontend/Sider/Behandling/Vilkårvurdering/JaNeiVurdering.tsx
- src/frontend/komponenter/Ikoner/Vilkårsresultat/VilkårsresultatIkon.tsx
- src/frontend/komponenter/Skjema/Select.tsx
- src/frontend/komponenter/Skjema/SelectMedOptions.tsx
Skal ha kort i stedet for tabellvisning av inngangsvilkår
Funksjonalitet som er endret: 
- Sletting skjer nå inne i redigeringsmodus. 
- Begrunnelse rett på vurdering er slettet (må testes sammen med [denne](https://github.com/navikt/tilleggsstonader-sak/pull/271) om du vil at ting skal funke)
- Samle ting på et kort som skissene
Kommer: 
- Vise tydligere at begrunnelse er påkrevd (må diskuteres om det skal prioriteres nå)
- Fjerne sykepenger vilkår
- En del renaming men vil gjøre det i egen pr så det er lettere å se - se todo kommentarer om hva jeg vil endre til
Ny aktivitet: 
Redigering av eksisterende aktivitet:
Hvordan ulike statuser ser ut: 
Ny målgruppe: 
Rediger: 
Ulike statuser:
> 💄 Nytt design på inngangsvilkår

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
Fjernet param `$lesevisning` då den likevel ikke brukes. Den kan ev. brukes for å ikke bruke en wrapping div som denne løsning gjør, men føler det blir mer styr, då man må bruke props 2 steder.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20570
> 🐛 Lesevisning av utgiftsrader

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeVilkår.tsx
Kan preutfylles fordi vi egentlig ikke vet hvilke andre regelverk som kan gjøre at dette blir ja ([favro](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20588))
> Preutfyll dekket av annet regelverk til nei

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/Begrunnelse.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/EndreVilkårperiodeInnhold.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/EndreVilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/validering.tsx
Om en begrunnelse er obligatorisk skal det listes opp grunnene til dette og gi en feilmelding dersom man prøver å lagre uten å fylle ut:
> Validering og visning av obligatorisk begrunnelse

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx
- src/frontend/Sider/Behandling/lenker.ts
- src/frontend/komponenter/VilkårPanel/VilkårPanel.tsx
> 💄 Samle aktivitet og målgruppe i en container

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Aksjonsknapper.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
Siden vi har gått vekk fra tabelldesign på inngangsvilkår skal heller ikke stønadsperiodene ha dette. 
Det er en tanke om at lagring av stønadsperioder og ferdigstille steg skal slås sammen, men fordi det ikke var en quick fix å gjøre som å bare slette tabellen blir det en oppgave for senere. Ser litt rart ut atm fordi det er så mye knapper og den ikke har egen ramme/container, men er like mange klikk og samme flyt som før
Under redigering: 
Ikke redigering:
> 💄 Stønadsperioder skal ikke lenger vises som tabell

- src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrev.tsx
Skal vise tittel i dokumentoversikt/gosys.
To første brev er sendt uten fix, det siste med:
> 🐛 Skal bruke brevtittel som beskrivelse for frittstående brev

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/AvslåVedtak.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeVedtak.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/VedtakOgBeregningBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/utils.ts
- src/frontend/Sider/Behandling/VedtakOgBeregning/Felles/SelectVedtaksresultat.tsx
- src/frontend/hooks/useVedtak.ts
- src/frontend/typer/vedtak.ts
- src/frontend/utils/utils.ts
Det skal være mulig å sette et vedtak til avslag. Hører sammen med [PR 296 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/296).
Var ingen skisser på dette enda, så har kun laget et tekstfelt med begrunnelse som tekstfelt som en start, med read only for leservisning. 
Om steget ikke er redigerbart/leservisning:
> ✨ Vedtak med resultat avslag 

- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Aktivitet.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Oppsummering.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Visningskomponenter.tsx
- src/frontend/typer/behandling/behandlingFakta/faktaAktivitet.ts
Vise aktivitet som fakta i venstremeny.
Denne PR testes sammen med: https://github.com/navikt/tilleggsstonader-sak/pull/295
****
****
****
> Vise aktivitet som fakta i venstremeny

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/EndreVilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/validering.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/aktivitet.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/målgruppe.ts
- src/frontend/komponenter/Skjema/DateInput.tsx
- src/frontend/utils/dato.ts
Det skal være mulig å velge "ingen aktivitet" eller "ingen målgruppe" slik at vi kan registrere at vilkår ikke er oppfylt. 
Ved valg av ingen aktivitet/målgruppe: 
- Fom = tre måneder tilbake i tid
- Tom = dagens dato
- Aktivitetsdager skal ikke settes
Må merges etter [PR 305 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/305)
Under redigering: 
Obligatorisk begrunnelse: 
Lagret:
> Avslag: Ingen målgruppe eller ingen aktivitet ❌

- src/frontend/Sider/Behandling/BehandlingContainer.tsx
- src/frontend/Sider/Behandling/BehandlingInnhold.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/utils.ts
- src/frontend/Sider/Behandling/VedtakOgBeregning/Felles/SelectVedtaksresultat.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Oppsummering.tsx
- src/frontend/context/BehandlingContext.ts
- src/frontend/typer/behandling/behandlingFakta/behandlingFakta.ts
- src/frontend/utils/dato.ts
Tilbakemeldinger etter funksjonell testing
Fom og tom på vilkårperioder skal preutfylles ved valg av "ingen aktivitet" eller "ingen målgruppe". De preutfylles nå med tre mnd tilbake -> d.d. En saksbehandling gjort i dag ville altså fått 15.02.24 - 15.05.24. 
Det riktige her er å sette fom = første dagen i måneden som er tre måneder før søknadstidspunkt:
- Søknad sendt inn 01.05, 10.05 og 25.05 skal alle få _fom=01.02_
- Søknad sendt inn i løpet av juni skal få 01.03
For å få til dette måtte man ha `søknadstidspunktet` og dette ble lagt i `behandlingFakta` (se [pr 313 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/313))
- Flyttet `behandlingFakta` inn i `BehandlingContext` slik at dato er tilgjengelig både for oppsummering og inngangsvilkår
- La til søknadsdato i oppsummering …
> Utled fom-dato på ingen aktivitet/målgruppe basert på søknadstidspunkt

- src/frontend/Sider/Oppgavebenk/filter/Oppgavefiltrering.tsx
- src/frontend/Sider/Oppgavebenk/typer/oppgavetema.ts
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20860
Tok i bruk optgroup for å splitte vanlige og øvrige oppgaver. 
Foreslå dette for Marie og hon tyckte ble ok.
> Delt opp oppgavetyper i 2 ulike grupper. De viktigste blir vist først

- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Aktivitet.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/ArbeidOgOpphold.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/BarnDetaljer.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Hovedytelse.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Oppsummering.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringSøknad.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Vedlegg.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Visningskomponenter.tsx
- src/frontend/Sider/Behandling/Venstremeny/Venstremeny.tsx
Det er ikke nødvendig å ha med alle søknad-ikonene når all informasjonen er fra søknaden. [FAVRO](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20852)
Mer vanlig situasjon: 
Mer info:
> Fjern ikoner og fiks spacing i venstremeny

- src/frontend/Sider/Oppgavebenk/Oppgaverad.tsx
- src/frontend/Sider/Oppgavebenk/Oppgavetabell.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a
Har notert i oppgaven for på-vent-oppgaver at kolonnen skal være med.
> Fjerner kolonne for frist og sorterer oppgaver etter opprettet tidspunkt

- src/frontend/Sider/Oppgavebenk/Oppgavebenk.tsx
- src/frontend/Sider/Oppgavebenk/Oppgavetabell.tsx
- src/frontend/Sider/Oppgavebenk/filter/Oppgavefiltrering.tsx
- src/frontend/Sider/Oppgavebenk/filter/filterutils.ts
- src/frontend/Sider/Oppgavebenk/filter/oppgavefilterStorage.ts
- src/frontend/Sider/Oppgavebenk/oppgaverequestUtil.ts
- src/frontend/Sider/Oppgavebenk/typer/oppgave.ts
- src/frontend/context/OppgaveContext.ts
Tidligere hentet vi 150 oppgaver fra oppgavesystemet, som oppgavebenken selv hadde paginering og sortering av.
Ulempen er hvis det finnes totalt 1000 oppgaver. Då får man bare hentet 150 uansett. hvis man endrer sorteringen i frontend vil man fortsatt kun gjøre den sorteringen på de siste 150 oppgavene, og ikke alle 1000.
Var litt vanskelig å splitte opp commitsen. Den mest spesielle er kanskje
* https://github.com/navikt/tilleggsstonader-sak-frontend/commit/bff25fd838dd0b56fe68f08dd368c6fb5ae24e98
Jeg kan godt ta en gjennomgang hvis det er ønskelig. 
https://github.com/navikt/tilleggsstonader-sak/pull/319
Litt koblet til Litt koblet til https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20858 men er mer som et steg 1 i den endringen.
> Oppgavebenk paginering med api kall

- src/frontend/Sider/Personoversikt/Dokumentoversikt/DokumentRad.tsx
- src/frontend/Sider/Personoversikt/Dokumentoversikt/DokumentTabell.tsx
- src/frontend/Sider/Personoversikt/Dokumentoversikt/Dokumentoversikt.tsx
- src/frontend/Sider/Personoversikt/Dokumentoversikt/Underrad.tsx
- src/frontend/utils/utils.ts
for å vise at vedlegg ble sendt sammen med en søknad.
I stor grad kopiert fra ef-sak-frontend, men litt annerledes fordi vi bruker tabell fra aksel.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20753
> ✨ Grupper dokumeneter etter journalpostId, og sorter på tid

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
- src/frontend/Sider/Behandling/Felles/VarselVedtakIArena.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
- src/frontend/Sider/Behandling/SettPåVent/SettPåVentInformasjon.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/OppsummeringStønadsperioder.tsx
- src/frontend/typer/behandling/behandlingFakta/behandlingFakta.ts
- src/frontend/typer/behandling/behandlingFakta/faktaArena.ts
- src/frontend/utils/dato.ts
For å unngå at saksbehandler legger inn overlappende vedtak er det ønskelig å vise informasjon om at det finnes vedtak i Arena.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21211
* https://github.com/navikt/tilleggsstonader-sak/pull/335
> Viser varsel hvis person finnes i Arena med innvilget vedtak

- src/frontend/Sider/Behandling/Brev/Brevmeny.tsx
Fordi `mellomlagredeInkluderteDelmaler` var en dependency i en useEffect, og denne blir kalkulert for hver render ble useEffecten også trigget for hver render 🔁 😞  Dette gjorde at man aldri rakk å generere brev før siden rendres på nytt
> 🐛 Skal memoisere parset mellomlagret brev for å unngå evig useEffect loop

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/VarselBarnUnder2år.tsx
- src/frontend/typer/behandling/behandlingFakta/faktaBarn.ts
- src/frontend/typer/vilkårsoppsummering.tsx
Skal vise varsel om det finnes barn med alder under 2 år. 🤟 
`alder` finnes allerede i fakta. Alder er alder ved tidspunktet grunnlaget blir opprettet. Mulig vi burde forholde oss til et annet dato. Har sendt en melding på slack. https://nav-it.slack.com/archives/C05TU86SU8Y/p1717499817280099
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21255
> Skal vise varsel om at det finnes barn under 2 år

- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/RegisterYtelser.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/RegisterYtelserTabell.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/RegisterAktivteter.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/RegisterAktivteterTabell.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts
- src/frontend/typer/registerytelser.ts
Viser frem alle registrerte ytelser for en bruker på inngangsvilkårside for å hjelpe saksbehandler
⚠️ "Bruk" ytelse kommer senere. Det bør testes før det brukes i prod så dette er kun en tabell som viser frem informasjonen. 
Hvis ingen registrerte perioder: 
Hvis grunnlagsdata ikke laget (behandlinger som er ferdigstilt før vi begynte med dette):
> ✨ Vis relevante ytelser på inngangsvilkår

- src/frontend/Sider/Oppgavebenk/Oppgaverad.tsx
- src/frontend/Sider/Oppgavebenk/typer/oppgavetema.ts
I oppgavebenken skal klager vises med "Oppgavetype": "Behandle sak (klage)". Dette gjøres for at det skal være tydelig for saksbehandler at oppgaven gjelder en klage, og at man sendes videre til klage-løsningen dersom man klikker på den.
> Vise klagesaker med egen Oppgavetype i Oppgavebenken

- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
En del av [dette](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21411) kortet. 
**Gjort:**
- Lagt til panel
- Aktivitet før målgruppe
- Vise tekst om at ingen stønadsperioder ble laget dersom steg ikke er redigerbart (denne var ikke en del av skissene, men tenkte det var greit å ikke ha et tomt panel)
**Ikke gjort:**
- Endring av knapper. Dette krever en samtale om hva man faktisk ønsker. Kan ikke fjerne "lagret visning" fordi det da ikke visualiseres for sb at endringer er lagret. Drar kortet tilbake til avklar behov og tar en prat med marie
Lagret: 
Under redigering: 
Ikke redigerbar behandling uten stønadsperioder:
> Stønadsperioder inn i panel og aktivitet før målgruppe

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/RegisterAktivteter.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/RegisterAktivteterTabell.tsx
- src/frontend/context/InngangsvilkårContext.ts
En omskrivning av hvordan "bruk register aktivitet" fungerer for å forklare bedre hva som skjer i #380.
Eneste endringen i funksjonalitet er at hvis du har en rad i redigeringsmodus får du beskjed om at du ikke kan legge til en ny ved trykk på "bruk", mens før skjedde det bare ikke noe. Her burde det kanskje ikke være mulig å trykke på knappen eller liknende, men må høre med noen™️ hva som er ønskelig oppførsel her siden disabled ikke er så poplært å bruke. Se bilde for forklaring.
Les commit for commit:
1. Trekk "bruk" ut av context
2. Slå sammen states for å holde styr på hvilken rad som redigeres
> ♻️ Bruk register aktivitet skal skje utenfor context

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/Sider/Behandling/Brev/Sanity/queries.ts
- src/frontend/Sider/Behandling/Brev/useBrev.ts
- src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrev.tsx
- src/frontend/typer/vedtak.ts
Så saksbehandler kun skal kunne velge relevante brevmaler
> ✨ Filtrering brevmaler

- src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingOversikt.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/FagsakOversikt.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettKlageBehandling.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettNyBehandlingModal.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettRevurderingBehandling.tsx
Det er ønskelig å kunne opprette revurdering
Har flyttet runt lite kode i `OpprettNyBehandlingModal` fordi jeg ønsker at "ny-<type>-behandling"-komponentene ansvarlige for sitt state, og at det ikke ligger i `OpprettNyBehandlingModal`. En egen commit for det.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21123
Koblet til
* https://github.com/navikt/tilleggsstonader-sak/pull/349
> Skal kunne opprette en revurdering

- .github/workflows/deploy-unleash-api-token-dev.yaml
- .github/workflows/deploy-unleash-api-token-prod.yaml
- .nais/dev.yaml
- .nais/prod.yaml
- .nais/unleash-apitoken-preprod.yaml
- .nais/unleash-apitoken-prod.yaml
Lagt til token for unleash.
Forskjellen mot sak er at `type: FRONTEND` som gir en litt annen type token sånn at man kan bruke `FlagProvider` fra https://github.com/Unleash/proxy-client-react
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21494
Koblet til:
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/386
> Nais-config for unleash

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx
- src/frontend/komponenter/Feil/Feilmelding.tsx
Hvis man har mange rader kan det være vanskelig å se feilmelding eller at det kommer en ny rad når man trykker "bruk".
Feilmelding scroll må ligge i `useEffect` fordi første gang feilmeldingen settes så er ref=null , men videre så endres ikke feilmeldingen seg så to-trykk håndteres ved at scroll også ligger i `settNyRadIRedigeringsmodus`
> 💄 Skal scrolle til ny rad og feilmelding på inngangsvilkår

- README.md
- package.json
- src/backend/auth/profile.ts
- src/backend/auth/token.ts
- src/backend/miljø.ts
- src/backend/server.ts
- src/backend/toggle.ts
- src/frontend/App.tsx
- src/frontend/utils/env.ts
- src/frontend/utils/toggles.ts
- src/frontend/utils/unleashMock.ts
- yarn.lock
Det er ønskelig å kunne toggle frontendfunksjonalitet med toggles. 
En forskjell mot EF er at jeg har tatt i bruk `FlagProvider`. Fra https://github.com/Unleash/proxy-client-react 
Bruker frackend for å proxya kall mot unleash direkte i stedet for å ha et endepunkt i sak-backend.
Fordelen med dette er at vi får metrics på kallene som utføres fra frontend og hvilke toggles som faktiskt er i bruk.
Den håndterer også refreshing av toggles jevnlig. Nå er den satt på 120s, men kan justeres. 
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21494
Koblet til
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/385
> Lagt til unleashklient for å kunne hente toggles

- src/frontend/Sider/Personoversikt/Dokumentoversikt/Dokumentoversikt.tsx
- src/frontend/typer/arkivtema.ts
- src/frontend/utils/toggles.ts
Saksbehandler ønsker å kunne se alle relevante dokumentposter. TSO og TSR skal være default. Ingen valgt henter foreløpig alle temaer, men det kan evt endres senere.
Har også fjernet oversikriften "Dokumentoversikt" etter ønske fra Marie.
> ✨ Skal kunne filtrere på teamer i dokumentoversikten.

- .eslintrc
- package.json
- src/frontend/Sider/Behandling/Stønadsvilkår/PassBarn/PassBarn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/VarselBarnUnder2år.tsx
- src/frontend/Sider/Oppgavebenk/typer/oppgavetema.ts
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx
Føler det skjer relativt ofte at vi får feil i loggene om en en eller annen `list.map(item => <div )` som mangler key.
Så tenker det hadde vært fint å unngå den med eslint. 
Kjørte også lint på alle filer som fikset noe tomme tegn.
> Lagt til eslint plugin react og validering av jsx-key

- src/frontend/Sider/Oppgavebenk/filter/oppgavefilterStorage.ts
Det er ønskelig at filter er nullstilte ved ny dag sån at det ikke henger igjen fra forrige dag.
Det er egentlige ønskelig at de nullstilles ved innlogging, jeg er usikker på om det virkelig er ønskelig og tror dette vil løste det største behovet. Er også usikker på hvordan det skulle blitt løst.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21261
Har også endret signaturen på metodene til å kun være koblet til OppgaveRequest nå når det finnes et felt for timestamp som kanskje ikke gjelder andre metoder som skal lagre til localStorage. Samtidig er også denne utilen nede blant oppgave-filene. 
Kan testes med å endre dato på feltet `_datoLagret` i local storage.
> LocalStorage av OppgaveRequest skal nullstilles ved ny dag

- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/SlettVilkårperiodeModal.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts
- src/frontend/context/InngangsvilkårContext.ts
Til nå har vi kun markert slettede vilkårperioder, men nå ønsker vi at de skal bli borte. 
Tilpasset for å ta i bruk endepunktet for permanent sletting i [PR 366 i backend](https://github.com/navikt/tilleggsstonader-sak/pull/366).
Landet på at det er best å starte med å fortsatt ha modal etter [diskusjon på slack](https://nav-it.slack.com/archives/C05TU86SU8Y/p1719828817727129). 
**Sletting av periode lagt til i denne behandlingen:** 
Før (nederste lagt til nå): 
Under sletting: 
Etter sletting vises ikke perioden at all: 
**Sletting av gjenbrukt periode:**
> ✨ Skal slette vilkårperiode permanent dersom den ble laget i denne behandlingen

- src/frontend/Sider/Klage/App/typer/fagsak.ts
- src/frontend/Sider/Klage/Komponenter/Behandling/Formkrav/VedtakSelect.tsx
- src/frontend/Sider/Klage/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx
- src/frontend/Sider/Klage/Komponenter/Behandling/Formkrav/utils.ts
- src/frontend/Sider/Klage/Komponenter/Behandling/Formkrav/validerFormkravUtils.ts
Fjerner uaktuell vedtakstype UTESTENGELSE fra klage-løsningen.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21768
> Fjerner påklaget vedtakstype UTESTENGELSE fra klage-løsningen

- src/frontend/App.tsx
- src/frontend/Sider/EksternOmruting/EksternOmruting.tsx
- src/frontend/Sider/EksternOmruting/EksternOmrutingBehandling.tsx
- src/frontend/Sider/EksternOmruting/EksternOmrutingSaksoversikt.tsx
- src/frontend/Sider/Klage/Felles/Visittkort/Status/StatusElementer.tsx
- src/frontend/Sider/Klage/Felles/Visittkort/Visittkort.tsx
I klage-appen er det lenker tilbake til personoversikten og behandlingen, men i kontekst av klage har vi ikke de interne UUID-ene som brukes i URL-en. 
Derfor har jeg nå laget en route under `/ekstern/*` som lar oss rute til saksbehandlingen basertt påekstern fagsak-ID, og påklaget vedtak (hvis et er valgt) basert på ekstern behandling-ID.
> Omruting til behandling og saksoversikt basert på eksterne ID-er

- src/frontend/Sider/Oppgavebenk/Oppgaverad.tsx
- src/frontend/Sider/Oppgavebenk/oppgaveutils.ts
- src/frontend/Sider/Oppgavebenk/typer/oppgave.ts
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaveliste.tsx
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaveoversikt.tsx
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/utils.ts
- src/frontend/Sider/Personoversikt/PersonoversiktInnhold.tsx
- src/frontend/utils/toggles.ts
Har lagt til en enkel tabell som ramser opp alle oppgaver som finnes på bruker på TSO. 
Den henter mapper selv for å få vist mappenavn. Lånt fra EF fordi det ikke var rett frem å sammenligne mappene i backend.
> Oppgaver på personoversikt

- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaveoversikt.tsx
Fortsettelse på #431
Gjør det mulig å hente oppgaver og mapper på nytt uten å refreshe hele siden.
> Legg til knapp for å hente oppgaver og mapper på nytt

- src/frontend/Sider/Behandling/Venstremeny/Historikk/Metadata.tsx
- src/frontend/Sider/Behandling/Venstremeny/Historikk/typer.tsx
Ønskelig å se kommentaren for satt på vent i historikken slik at man har den tilgjengelig når man tar behandlingen av vent. 
Fra diskusjon på [slack](https://nav-it.slack.com/archives/C05TU86SU8Y/p1721635186981229)
> Skal vise kommentar for sett på vent om behandling er redigerbar

- src/frontend/App.tsx
- src/frontend/Sider/Admin/OpprettBehandlingFraJournalpost.tsx
- src/frontend/Sider/Personoversikt/Dokumentoversikt/DokumentRad.tsx
- src/frontend/typer/ressurs.ts
- src/frontend/utils/toggles.ts
Det finnes mange søknader som har kommit inn via fyll ut/send inn, som har fått opprettet en sak med vedtak som ikke har noe status ennå i Arena.
Disse skal behandles i ny løsning
For å kunne gjøre det er det ønskelig med en knapp som kan opprette en behandling fra journalpostId som henter barnen fra søknaden og oppretter en behandling med disse.
Skal ikke håndtere papirsøknad nå. Då barnen manuellt må legges inn. 
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21648
https://github.com/navikt/tilleggsstonader-sak/blob/main/src/main/kotlin/no/nav/tilleggsstonader/sak/behandling/manuell/OpprettBehandlingFraJournalpostService.kt
> Opprett førstegangsbehandling fra journalpostid

- src/frontend/Sider/Behandling/Venstremeny/Dokumentoversikt/DokumentKomponenter.tsx
- src/frontend/Sider/Behandling/Venstremeny/Dokumentoversikt/Dokumentliste.tsx
- src/frontend/Sider/Behandling/Venstremeny/Dokumentoversikt/Dokumentoversikt.tsx
- src/frontend/Sider/Behandling/Venstremeny/Venstremeny.tsx
- src/frontend/Sider/Personoversikt/Dokumentoversikt/DokumentTabell.tsx
- src/frontend/Sider/Personoversikt/Dokumentoversikt/Dokumentoversikt.tsx
- src/frontend/Sider/Personoversikt/Dokumentoversikt/utils.ts
- src/frontend/typer/arkivtema.ts
- src/frontend/typer/dokument.ts
Enkel tilgang til alle dokumenter og vedlegg fra en behandling. 
Har flyttet noen av funksjonene som er brukt i dokumentoversikten på personoversikten ut til utils for å kunne bruke begge steder. 
Henter alle "relevante" dokumenter (samme som dokumentoversikten)
> ✨ Dokumentoversikt i behandling

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/RegisterYtelser.tsx
- src/frontend/Sider/Personoversikt/Ytelseoversikt/YtelserTabell.tsx
- src/frontend/typer/registerytelser.ts
Vi henter perioder fra AAP som gir rett på våre stønader
Dersom en periode har aktivitetsfase "ferdig avklart" gir den ikke rett på tilsyn barn.
Dersom man henter periodene til personoversikten er det fortsatt ønskelig å vise informasjonen.
Dersom man henter de som grunnlag til behandlingen så er det ikke ønskelig å vise de.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21588
* https://github.com/navikt/tilleggsstonader-integrasjoner/pull/109
* https://github.com/navikt/tilleggsstonader-sak/pull/388
> AAP-perioder info om aktivitetsfase ferdig avklart 

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/FagsakOversikt.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettNyBehandlingModal.tsx
- src/frontend/Sider/Personoversikt/PersonoversiktInnhold.tsx
- src/frontend/context/BehandlingContext.ts
- src/frontend/context/StegContext.ts
Nå vises endringsknapper inne på en behandling for de som kun er veileder, som ikke er ønskelig. 
Usikker på om vi må skjule oppgaver for veiledere, men ettersom ikke oppgavebenken vises for veiledere fjerner jeg den fra personoversikten og.
> Veiledere skal ikke kunne utføre endringer på en behandling

- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Arena/OppgavelisteArena.tsx
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Arena/OppgaverArena.tsx
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Arena/typer.ts
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaveoversikt.tsx
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaver.tsx
- src/frontend/utils/toggles.ts
Det er ønskelig å kunne vise oppgaver i Arena i personoversikten for å kunne vite om personen har åpne oppgaver i Arena
* https://github.com/navikt/tilleggsstonader-arena/pull/35
* https://github.com/navikt/tilleggsstonader-sak/pull/393
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21779
> Oppgaver fra Arena i personoversikten

- src/frontend/App.tsx
- src/frontend/Sider/Admin/OpprettFørstegangsbehandlingAdmin.tsx
- src/frontend/typer/identrequest.ts
- src/frontend/utils/toggles.ts
- src/frontend/utils/utils.ts
Det var tidligere mulig å opprette førstegangsbehandling fra journalpostId via admin.
Vi har haft noen tilfeller der det finnes papirsøknad eller søknad fra EF der det også er ønskelig å opprette førstegangsbehandling. 
For å støtte dette kan man då opprette basert fra ident. Og då velge hvilke barn som skal være med på behandlingen.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21972
* https://github.com/navikt/tilleggsstonader-sak/pull/394
> Admin opprett førstegangsbehandling

- src/frontend/Sider/Personoversikt/Behandlingsoversikt/FagsakOversikt.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/BarnTilRevurdering.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettNyBehandlingModal.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettRevurderingBehandling.tsx
- src/frontend/typer/behandling/behandlingÅrsak.ts
Det er ønskelig å kunne velge barn når man oppretter en revurdering.
Vi gjenbruker data fra forrige behandling. I tilfelle det i en første behandling er behandlet 1 barn, og i en ny søknad kommer et nytt barn, så må man kunne legge til denne til den nye behandlingen
Vi har noen ulike situasjoner:
* Mottatt papirsøknad
* En digital søknad for revurdering har blitt journalført men ikke fått opprettet behandling
* Søknad til barnetilsyn fra enslig forsørger
I tillegg så har vi mulighet for å kunne opprette førstegangsbehandling med barn fra admin-funksjonalitet. Det er mulig det blir flyttet hit en gang. 
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21972
* https://github.com/navikt/tilleggsstonader-sak/pull/398
Hvis man ønsker å teste de nå …
> Revurdering velge barn

- src/frontend/Sider/Behandling/Simulering/SimuleringResultatWrapper.tsx
Skal hente behandling på nytt, for å oppdatere behandlingen med riktig steg så man kan navigere til brevfanen uten å refreshe siden.
Føles litt unødvendig å måtte gjøre dette, så tar gjerne forslag til alternative løsninger.
> Hent steg etter simulering

- src/frontend/Sider/Oppgavebenk/filter/Oppgavefiltrering.tsx
Det er tenkt at select skal gjøre det tydligere enn checkbox.
Vi valgte å kun kunne velge `Klar` eller `På vent`. Å kunne vise "Alle" trenger api-endringer.
* https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21728
> Det er ønskelig med select for å velge klar eller på-vent benk

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/Sider/Behandling/Brev/brevUtils.ts
- src/frontend/typer/vedtak.ts
Til nå henter vi kun brev basert på resultatet (type) på vedtaket.
For å vise revurderingsbrev må vi også se på behandlingType
> Returner REVUDERING-mappe i sanity dersom behandlingen er en revurdering

- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/NyttVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx
- src/frontend/context/VilkårContext.ts
Det er ønskelig å kunne slette et vilkår som er opprettet i den samme behandlingen for å fjerne et vilkår i tilfelle det har blitt opprettet ved en feil.
Sletting av vilkår opprettet i tidligere behandlingen blir kanskje utført i en senere endring
❗ Denne kan kun merges etter at backend ikke oppretter vilkår automatisk når man går inn på vilkårsiden. 
Det må dog gjøres etter at man har aktivert vilkårperiode sånn at man ikke fjerner vilkår i prod uten mulighet for å kunne legge til et vilkår
> Slette vilkår opprettet i denne behandlingen

- src/frontend/Sider/Behandling/Brev/Sanity/queries.ts
- src/frontend/Sider/Behandling/Brev/brevUtils.ts
- src/frontend/Sider/Behandling/Brev/useBrev.ts
- src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrev.tsx
Quickfix. Ønsker å vise innvilgelsesmalene også det er en revurering.
Testet lokalt:
> Hent innvilgelsesmaler for revurdering

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/komponenter/Brevmottakere/BrevMottakere.tsx
- src/frontend/komponenter/Brevmottakere/BrevmottakereListe.tsx
- src/frontend/komponenter/Brevmottakere/SkalBrukerHaBrev.tsx
- src/frontend/komponenter/Brevmottakere/SøkOrganisasjon.tsx
- src/frontend/komponenter/Brevmottakere/SøkPerson.tsx
- src/frontend/komponenter/Brevmottakere/brevmottakerUtils.ts
- src/frontend/komponenter/Brevmottakere/typer.ts
- src/frontend/utils/fomatering.ts
- src/frontend/utils/toggles.ts
Åpner opp for lagring av brev-mottakere i SAK-backend:
Sees i sammenheng med PR: https://github.com/navikt/tilleggsstonader-sak/pull/403
> Endring av brevmottakere i SAK

- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Arena/OppgavelisteArena.tsx
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Arena/OppgaverArena.tsx
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaveliste.tsx
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaver.tsx
- src/frontend/Sider/Personoversikt/PersonoversiktInnhold.tsx
- src/frontend/komponenter/PersonHeader/PersonHeader.tsx
- src/frontend/utils/dato.ts
Personoversikten trenger en liten gjennomgang for å bedre matche skissene. 
[favro-oppgave](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22179)
Jeg stareter med oppgavelista - [se skisse her](https://www.figma.com/design/7eVA9o9YdfQi7MRuzx9wWu/TS-sak%3A-Personoversikt?node-id=1-7681&t=DSPXboKKo6me2LQO-4)
**Gjort i denne PR-en:** 
- Endrer faneoverskrifter
- Gjør maks-bredden til tabellene større
- Legger til overskrift 
- Legger til oppdateringstidspunkt
- Flytter personoversikten-lenka fra ident til navn
**Dette er _ikke_ gjort i denne PR-en, og jeg er usikker på om vi egentlig trenger å gjøre det nå:** 
- Gjøre tabellen sorterbar 
- Legge inn knapp for å gå til Gosys og Arena 
Før: 
Etter:
> 💅 Personoversikt del 1 - oppgaver

- src/frontend/Sider/Behandling/Simulering/Oppsumering.tsx
- src/frontend/Sider/Behandling/Simulering/ResultatVerdi.tsx
- src/frontend/Sider/Behandling/Simulering/Simulering.tsx
- src/frontend/Sider/Behandling/Simulering/SimuleringResultatWrapper.tsx
- src/frontend/Sider/Behandling/Simulering/SimuleringTabell.tsx
- src/frontend/Sider/Behandling/Simulering/simuleringTyper.ts
Vil sammenstille informasjon fra simulering så saksbehandler forstår om det blir feilutbetaling og det evt. må nevnes i brev.
Alert om feilutbetaling kommer i egen PR.
> ✨ Vis oppsummering av simuleringen

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/komponenter/Brevmottakere/BrevMottakere.tsx
Endrer Layout på Brevsiden etter innspill fra Tone.
Har ikke sjekket hvordan dette ser ut i Klage-løsningen enda
**Update: ** Endret så det er samme layout på både 1 og flere mottakere. Fjernet alert og gjort knapp mindre
FAVRO: https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22520
******
**FØR**:
******
**ETTER**:
En brevmottaker: 
Flere brevmottakere:
> Endrer Layout på brevsiden etter tilbakemelding fra saksbehandler

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/EndreVilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeRad.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår.tsx
- src/frontend/komponenter/Visningskomponenter/Celle.tsx
Før fikk feilmeldingene så mye plass de ønsket og dyttet andre felter vekk: 
Etter:
> 💄 Feilmeldinger skal ikke påvirke visning av 

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/EndreVilkårperiodeRad.tsx
- src/frontend/komponenter/Visningskomponenter/FeilmeldingFastBredde.tsx
Så slik ut på saksbehandlernes pc: 
**Problem:**
Datovelgeren ser ut som den har fast bredde basert på ✨ noe ✨ men den er ulik på ulike pcer, så bruk av celle gjorde at den lå oppå hverandre for de. 
**Løsning:**
Lage en wrapper som setter bredden direkte på feilmeldingen i de tilfellene det er nødvendig. 
Ser fortsatt helt likt ut som det i originalpr hvor dette ble prøvd fikset:
Innså at det samme gjalt stønadsperioder så de er også stylet litt
|FØR|ETTER|
|---|---|
|<img width="1140" alt="image" src="https://github.com/user-attachments/assets/8df43b5f-960c-4ba2-a906-66c2b090f2ba">|<img width="858" alt="image" src="https://github.com/user-attachments/assets/967858c7-9b1a-46bc-87ba-2bd2c41fe9fd">|
> Feilmeldinger styling

- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/OppsummertVilkårsvurdering.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/VilkårperiodeKortBase.tsx
Før viste vi ikke kommentaren som ble lagt inn ved sletting av en vilkårperiode
> Skal vise hvorfor en periode er slettet

- src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/FagsakOversikt.tsx
- src/frontend/utils/behandlingutil.ts
Når en klagebehandling får et resultat fra kabal ønsker vi å vise dette i behandlingsoversikten.
Har kopiert fra EF.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22481
(Denne er ikke faktisk feilregistret, men ville bare vise ikonet)
> ✨ Resultat kabal behandlingsoversikt

- src/frontend/Sider/Behandling/Stønadsvilkår/PassBarn/PassBarn.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringLæremidler.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringSøknad.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringTilsynBarn.tsx
- src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Utdanning.tsx
- src/frontend/typer/behandling/behandlingFakta/behandlingFakta.ts
- src/frontend/typer/behandling/behandlingFakta/faktaUtdanning.ts
Sees i sammenheng med denne PR: https://github.com/navikt/tilleggsstonader-sak/pull/452
******************
**FAKTA LÆREMIDLER**
******************
**FAKTA BARNETILSYN**
> Forskjellig visning for fakta tilsynbarn og laremidler

- src/frontend/Sider/Behandling/BehandlingInnhold.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/FyllUtVilkårKnapp.tsx
- src/frontend/Sider/Behandling/Stønadsvilkår/Stønadsvilkår.tsx
- src/frontend/context/VilkårContext.ts
Stønadsvilkår (pass av barn) lastes ikke inn på nytt når man endrer revurder fra. Dette gjør at man ikke får endre på noen av vilkårene fordi de ikke lenger eksisterer og de nye ikke blir hentet. 
Løsning: 
- Flyttet context inn
- Bonus: Context forholder seg ikke lenger til ressurs
> Flytt vilkårcontext så det først lastes når side besøkes

- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Aksjonsknapper.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/LesMerStønadsperioder.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
- src/frontend/Sider/Behandling/Stønadsvilkår/OppsummeringStønadsperioder.tsx
- src/frontend/Sider/Behandling/Stønadsvilkår/PassBarn/PassBarnLesMer.tsx
Vi skal gå vekk fra ordet "stønadsperiode". FOM mandag skal vi ta i bruk "overlappsperiode" (kun internt) og "Periode med overlapp mellom aktivitet og målgruppe" o.l. formuleringer visuelt i løsningen. 
I første omgang fjerner jeg bruken av ordet visuelt. Byttet ut med en blanding av formuleringen over og bare bruk av ordet "periode". Har også oppdatert readMores som ikke lenger var aktuelle med nye regler. 
⚠️ Har sparret med Marie om tekstene underveis
> 💄 Fjern visuell bruk av ordet "stønadsperiode"

- src/frontend/Sider/Oppgavebenk/filter/Oppgavefiltrering.tsx
- src/frontend/Sider/Oppgavebenk/typer/oppgave.ts
Ønsker mulighet for å filtrere på klage i oppgavebenk.
Ingen filtrering (som tidligere):
Filtering på behandlingstype "klage" (nytt):
Filtering på oppgavetype (som tidligere):
> Legg til mulighet for å filtrere på klage i oppgavebenk

- src/frontend/Sider/Behandling/Simulering/useSimuleringÅrvelger.ts
Informasjonen for inneværende år er mest interresant. Oppsummeringsboksen "Totalt for perioden" kan brukes for å raskt se feil i kommende år.
> Oppdater simuleringssiden slik at den default viser inneværende år

- package.json
- src/frontend/Sider/Klage/Steg/Brev/PdfVisning.tsx
- src/frontend/komponenter/PdfVisning.tsx
- tsconfig.json
- yarn.lock
Oppdatert til ES2022 for å kunne ta inn nye endringen på PDFVisning og er litt nyere enn es6 (ES2015)
EF utførte de samme endringene i juni. https://github.com/navikt/familie-ef-sak-frontend/pull/2775
> Oppdatert react-pdf

- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/tekstmapping.ts
- src/frontend/Sider/Behandling/Vilkårvurdering/LesevisningVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/Vurderingsrad.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/tekster.ts
Det blir mindre scrollebehov hos saksbehandlerne. 
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22883
> Gjør lesevisningen av Pass barn-tabellen mer kompakt

- src/frontend/Sider/Behandling/Vilkårvurdering/tekster.ts
Vilkåret passer nå bedre med lovverket
Frontend:
Pdf:
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22824
https://github.com/navikt/tilleggsstonader-sak/pull/474
> Oppdater ordlyden i vilkåret om dokumentasjon av utgifter til pass

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/RegisterAktivteter.tsx
* Oppdaterer tittel
* Legger lenken til Personoverikten inni Hjelpeteksten
Ny versjon:
*********
Gammel versjon:
> Oppdaterer tittel på aktiviteter, og legger lenken til personoversikten inni hjelpeteksten

- src/frontend/Sider/Journalføring/Standard/Journalføring.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23094
Etter journalføring ble oppgavebanken filtrert med det ID-nummeret knyttet til den journalføring oppgave. Så det var bare å vise alle oppgavene knyttet til det ident nummeret. For å få alle oppgavene måtte vi klikke på nullstill-filtre hele tiden. 
Nå trenger vi ikke gjøre det. Etter journalføring blir den automatisk omdirigert til oppgavebenk og vi kan se alle oppgavene til alle ident nummerene.
> Fjernet ident fra local storage etter journalføring i Journalføring.tsx

- src/frontend/Sider/Behandling/Brev/Valgfelt.tsx
Hvis man har gjort et valg i et valgfelt så er det ikke mulig å gå tilbake til å "ikke ha valgt noe", som er uheldig de stedene valgfeltene brukes for å "huke av og på informasjon" og det å ta et valg er valgfritt.
> Skal kunne nullstille valg i valgfelt

- src/frontend/Sider/Behandling/Brev/brevUtils.ts
- src/frontend/Sider/Behandling/Brev/typer.ts
- src/frontend/Sider/Klage/Steg/Brev/Brev.tsx
- src/frontend/Sider/Klage/typer/personopplysningerFraKlage.ts
- src/frontend/hooks/useHentFullmektige.ts
- src/frontend/komponenter/Brevmottakere/EndreBrevmottakereModal.tsx
- src/frontend/komponenter/Brevmottakere/VergerOgFullmektigeFraRegister.tsx
- src/frontend/komponenter/Brevmottakere/brevmottakerUtils.ts
- src/frontend/komponenter/Brevmottakere/typer.ts
- src/frontend/typer/fullmakt.ts
- src/frontend/typer/personopplysninger.ts
- src/frontend/typer/ressurs.ts
Det var misledende, og en potensiell feilkilde, at fullmakter var en del av PDL-responsen, ettersom dissse dataene er utdaterte. Nå hentes i stedet brevmottakere i klage og i ts-sak fra et nytt endepunkt `/fullmektige`
Hvis alt funker:
Hvis noe går galt ved uthentingen:
> Fullmaktsmottakere

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/valideringAktivitet.tsx
Gikk ikke å lagre "ingen aktivitet" fordi det var en feilmelding som ikke gikk å lagre
> 🐛 Skal ikke validere aktivitetsdager hvis type er ingen aktivitet

- src/frontend/Sider/Behandling/Brev/brevUtils.ts
Gjøre det enklere for saksbehandler å finne rett brevmal ved opphør
> Kun vis opphørsbrevmal hvis vedtaket er et opphør

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/OpphørVedtak.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/VedtakOgBeregningBarnetilsyn.tsx
> Ikke brekk layout når opphør feilmelding vises

- src/frontend/Sider/Oppgavebenk/filter/oppgavefilterStorage.ts
Saksbehandlerne er gjerne på 'Ventebenk'-vakt og skal gå gjennom alle saker på vent. Når man har behandlet en sak på vent ønsker saksbehandler å komme tilbake til oppgavebenk, og filteret for 'Benk - På vent' er fortsatt på.
> Behold 'på-vent' filteringen ved refresh

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetBarnetilsyn.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetLæremidler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreFellesFelter.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreTypeOgDatoer.tsx
Vi lagde EndreFellesFelter for å unngå duplikat mellom EndreAktivitetBarnetilsyn og EndreAktivitetLæremidler, men disse fellesfeltene finnes også på målgruppe. Så ved å gjøre filen litt mer generell kan den brukes av begge.
**OBS:** lukket #592 for å gjøre det litt ryddigere. Har gjort typen generisk så vi slipper casting ⭐
> Fellesfelter målgruppe

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Delvilkår/AktivitetDelvilkårBarnetilsyn.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Delvilkår/AktivitetDelvilkårLæremidler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetBarnetilsyn.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetLæremidler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsBarnetilsyn.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsLæremidler.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/valideringAktivitetBarnetilsyn.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/valideringAktivitetLæremidler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeVilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/valideringMålgruppe.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/aktivitet.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/målgruppe.ts
- src/frontend/Sider/Behandling/Vilkårvurdering/JaNeiVurdering.tsx
Ta i bruk de nye endepunktene laget i [PR 495 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/495)
Har splittet det opp i en commit per type/stønadstype, kan være fint å se på tilhørende util-fil samtidig.
PS: Fungerer ikke på lagremidler fordi mappingen av fakta og vurderinger ikke er implementer for læremidler enda.
> Nye endepunkter for å opprette og oppdatere vilkårperioder

- package.json
- src/backend/tsconfig.json
- src/backend/webpack/webpack.development.ts
- tsconfig.json
- webpack/webpack.production.js
- yarn.lock
Tatt i bruk https://github.com/privatenumber/esbuild-loader for å få raskere byggen.
Lokalt tok det meg ca 20-30s å starte, nå tar det ca 3s
Reload går også blazingly fast. 
`esbuild-loader` bruker default `ESNEXT`, samtidig som det er dokumentert at den skal bruke `tsconfig.json` der det er definiert at den skal bruke `es6`. `es6` virket heller ikke så har tatt i bruk `ES2022`
Det som feiler er `import.meta.url` som er undefined og fant ingen annen god løsning enn å bruke `ES2022` som burde gå fint. Ser flere andre prosjekter på NAV som også bruker det. 
```typescript
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
'pdfjs-dist/build/pdf.worker.min.mjs',
import.meta.url
).toString();
```
Brukte https://github.com/stephencookdev/speed-measure-webpack-plugin for å finne ut hva som tok lang …
> Tatt i bruk esbuild-loader for raskere bygge og reload

- package.json
- src/backend/tsconfig.json
- src/backend/webpack/webpack.development.ts
- tsconfig.json
- webpack/webpack.production.js
- yarn.lock
Måtte revertere overgangen til esbuild pga at den ikke feilet compile-time-errors, eller ts-errors
Opprinnelig PR, som er revertert x2
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/607
Det som manglet var https://github.com/TypeStrong/fork-ts-checker-webpack-plugin som var nevnt i 
https://github.com/privatenumber/esbuild-loader?tab=readme-ov-file#type-checking
Det brukes for å typesjekke filene i bygget.
Konfigurering er utført i https://github.com/navikt/tilleggsstonader-sak-frontend/commit/d4c80ecb1213fe7c65e93dc21321343308706f4a
- Dev har async true, sånn at den kjører parallellt med bygget, bygger selv om ts-check feiler
- Legger til absolute pathType for development for å få fulle lenker til filer som feiler
> Esbuild - lagt til fork-ts-checker-webpack-plugin for typesjekking og feile bygge ved feil

- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettNyBehandlingModal.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettNyBehandlingUtils.ts
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettOrdinærBehandling.tsx
Ved opprettelse av ny behandling via saksoversikten har man i realiteten anledning til å opprette både revurderinger og førstegangsbehandlinger. Idag må saksbehandler allikevel velge "Revurdering", selv om det faktisk opprettes en førstegangsbehandling.
I denne PR erstattes "Revurdering" med "Ordinær behandling", som skal representere både revurderinger og førstegangsbehandlinger.
FAVRO: https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23356
**ETTER:**
******
**FØR:**
> Erstatter "Revurdering" med "Ordinær Behandling" ved opprettelse av ny behandling

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/Sider/Klage/Steg/Brev/Brev.tsx
- src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrev.tsx
- src/frontend/hooks/useBrevmottakere.ts
Hver gang man utførte en endring i brevet så ble et kall trigget for å hente brevmottakere. Dette blir mange kall.
Tidligere ble objektet `context` opprettet på nytt hver gang man utførte en endring i brevet. Pga at `Brev` renderes på nytt.
Dette pga at `hentBrevmottakere` oppdateres hver gang `context` endrer seg, og dependency-list sjekker på objektpekere og ikke deep-check på objektet.
Hver context ligger nå i en memo, og trigger ev. endring av behandlingId/fagsakId.
Fjerne `context` fra `hentBrevmottakere` og `lagreBrevmottakere` sin `DependencyList`
Men på en måte føler jeg dette blir litt ryddigere
> Unngår henting av brevmottakere hver gang man endrer noe i brevet.

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetBarnetilsyn.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetLæremidler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsAktivitet.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsLæremidler.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/aktivitet.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/aktivitetLæremidler.ts
- src/frontend/Sider/Behandling/Stønadsvilkår/OppsummeringStønadsperioder.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Beregningsresultat.tsx
Reell arbeidssøker er ikke en gyldig aktivitet man skal kunne registrere på læremidler.
Løst ved å endre `aktivitetSelectOptions` til en funksjon som tar inn stønadstypen og finner alternativer basert på denne.
⚠️ Se commit for commit for å slippe litt kaos ved refaktor til ny fil i siste commit
> Fjern reell arbeidssøker som en valgmulighet for aktivitet på læremidler

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
- src/frontend/Sider/Behandling/Totrinnskontroll/Totrinnskontroll.tsx
- src/frontend/context/BehandlingContext.ts
- src/frontend/utils/toggles.ts
- src/frontend/utils/unleashMock.ts
Skal kunne toggle behandling og revurdering av spesifike stønadstyper
- Behandling er redigerbar dersom behandling er i riktig state og toggle er enabled, som er avhengig av om det er en revurdering eller vanlig behandling
- Skal alltid kunne sette en behandling på vent
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23509
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23476
> Toggle kan saksbehandle/revurdere stønader - læremidler

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Delvilkår/AktivitetDelvilkårLæremidler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetLæremidler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreStudinivå.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsLæremidler.ts
* Resetter felter dersom de ikke skal tas stilling til
* Skal ikke ta stilling til utstyrsstipend hvis "ingen aktivitet". Ikke noe vits å vurdere hvis brukeren ikke har aktivitet
* Har også trukket inn `erUtdanningEllerTiltak` i komponentene for å unngå at man sjekker type både utenfor komponenten, i `EndreAktivitetLæremidler` og inne i sub-komponentener
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23693
Denne mappes heller ikke i backend
`AktivitetType.INGEN_AKTIVITET -> IngenAktivitetLæremidler`
Denne endringen blir vel delvis fikset i https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23580 men får også endret sjekker
> Småfiks fakta og vurdering læremidler

- src/frontend/context/StegContext.ts
Alle faner låses for redigering i revurderinger som ikke har satt revurder fra-dato. 
Slik ser inngangsvilkårene ut dersom revurder fra ikke er satt:
Når https://github.com/navikt/tilleggsstonader-sak/pull/523 er merget vil det i tillegg komme feilmelding fra backend dersom SB forsøker å endre steg.
> ✅ Ingen steg er redigerbare i revurdering med mindre revurder fra-datoen er satt

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeHjelpetekst.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/målgruppe.ts
FAVRO: https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23603
Skal ikke vise "100% sykepenger" som mulig valg i dropdown dersom behandlingen gjelder Læremidler
Skal vise alternativ tekst dersom behandling gjelder Læremidler
*******
ETTER:
********
FØR:
> Hundre prosent sykepenger fjernes som maalgruppe for laremidler

- src/frontend/Sider/Behandling/Felles/VarselRevurderFraDatoMangler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
- src/frontend/Sider/Behandling/Stønadsvilkår/Stønadsvilkår.tsx
- src/frontend/komponenter/Stegflyt/StegKnapp.tsx
Et forslag som spinner ut fra https://github.com/navikt/tilleggsstonader-sak-frontend/pull/639#pullrequestreview-2502270615
Forslaget var at "Neste steg"-knappen skjules i en revurdering dersom ikke revurder fra-datoen er satt.
> ✨ Skjuler neste steg-knapp dersom steget er låst for redigering

- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgeLæremidler.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/Vedtaksperioder.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/validering.ts
For å gi tydligere melding til bruker på hva som er galt.
Før: 
Nå:
> Valider vedtaksperioder før de sendes til backend

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
- src/frontend/Sider/Behandling/Fanemeny/HamburgermenyBehandling.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/RegisterAktivteter.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/RegisterYtelser.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/OppdaterGrunnlag/OppdaterGrunnlagKnapp.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/OppdaterGrunnlag/useOppdaterGrunnlag.ts
- src/frontend/context/BehandlingContext.ts
- src/frontend/komponenter/Hamburgermeny/Hamburgermeny.tsx
- src/frontend/utils/toggles.ts
Det er ønskelig å kunne overstyre dato vedlegg hentes fra i en førstegangsbehandling då vi skal innvilge noen behandlinger fra og med 2020.
For revurdering brukes revurder-fra datoet.
Ikke peneste hamburgermenyn, er kopi fra klage. Men den virker. 
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23910
Koblet til
* https://github.com/navikt/tilleggsstonader-sak/commit/0162a42c1d65c56853c116497f62170fc996f545
https://github.com/user-attachments/assets/079cf69c-6be3-4dfe-835e-52685dbcc99d
> Skal kunne overstyre datoet som brukes for henting av grunnlag i en førstegangsbehandling

- src/frontend/context/ManglendeBrevVariablerContext.ts
Sånn at vi validerer alle variabler for å unngå at man sender brev der man ikke fylt i placeholders.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23991
> Legger til validering av variabler direkt i en delmal

- src/frontend/context/BrevFeilContext.ts
- src/frontend/komponenter/Brev/Brevknapp.tsx
- src/frontend/komponenter/Brev/DelmalMeny.tsx
- src/frontend/komponenter/Brev/Valgfelt.tsx
- src/frontend/komponenter/Brev/Variabler.tsx
- src/frontend/komponenter/Brev/typer.ts
Ønskelig å validere valgfelt
Har også lagt inn at felt som mangler verdi får error.
Fortsettelse på 
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/676
Avhengig av
* https://github.com/navikt/tilleggsstonader-brev-sanity/pull/68
Et alternativ er å bruke map i stedet for liste
* https://github.com/navikt/tilleggsstonader-sak-frontend/commit/f10ca1caf541f044eac820295335f5596dc09e53
> Brev validering valgfelt

- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/VedtaksperiodeRad.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/Vedtaksperioder.tsx
I en revurdering skal vi låse tidligere vedtaksperioder som man ikke skal kunne endre. 
På lik måte som andre perioder som blir låste.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a
Kan være fint å sjekke commit for commit. Første commit er oppsplitting av renderingen av hver rad for å sen kunne legge til `useRevurderingAvPerioder`
> Låsing av vedtaksperioder i innvilgelse i en revurdering av læremidler

- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgeLæremidler.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgelseLæremidlerEllerVedtaksperioderFraForrigeBehandling.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/VedtakOgBeregningLæremidler.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/vedtakLæremidlerUtils.ts
- src/frontend/hooks/useVedtak.ts
Når man skal innvilge en revurdering og forrige behandling er innvilgelse eller opphør trenger vi å vise vedtaksperiodene fra forrige behandling, og at de som er før revurder fra blir låste.
Fortsettelse på 
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/673
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23758
> Læremidler revurdering vis perioder forrige behandling

- src/frontend/Sider/Oppgavebenk/Oppgaverad.tsx
- src/frontend/Sider/Oppgavebenk/Oppgavetabell.tsx
- src/frontend/Sider/Oppgavebenk/typer/oppgave.ts
Det er ønskelig at saksbehandlere velger opphørsoppgaver først derfor ønsker vi å tagge disse før å gjøre det tydelig at det er et opphør. Dette gjelder kun godkjenn vedtak oppgaver.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23450
> Legg til opphørstag

- src/frontend/Sider/Behandling/SettPåVent/SettPåVentForm.tsx
- src/frontend/Sider/Behandling/Venstremeny/Historikk/Historikk.tsx
- src/frontend/context/BehandlingContext.ts
- src/frontend/hooks/useBehandlingshistorikk.ts
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22956
Formålet er å kunne trigge re-henting av historikk også når status på behandling ikke endrer seg, e.g. ved oppdatering av "sett på vent".
@sarahjelle har du anledning til å 👀?
> Løftet henting av behandlingshistorikk opp til BehandlingContext. 

- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StatusTag.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/stønadsperiode.ts
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgeLæremidler.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgelseLæremidlerEllerVedtaksperioderFraForrigeBehandling.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/VedtaksperiodeRad.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/Vedtaksperioder.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/validering.ts
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/vedtakLæremidlerUtils.ts
- src/frontend/komponenter/Skjema/DateInput.tsx
- src/frontend/komponenter/Skjema/DateInputMedLeservisning.tsx
- src/frontend/typer/behandling/periodeStatus.ts
- src/frontend/typer/vedtak/vedtakLæremidler.ts
- src/frontend/utils/periode.ts
I revurdering av læremidler må beslutter kunne se hvilke perioder som er endret og hvilke som er nye, på lik linje som for stønadsperiodene. 
Koden er satt opp slik at det kan merges inn uten å påvirke noe eksisterende. Det er først når backend begynner å sende "id" og "status" at tagsene trer i kraft. 
Ørlite eyetwitch at tagsene ikke er heeelt sentrert 🥲 Fant ikke ut av hvorfor det skjer. Noen med bedre forståelse av CSS enn meg kan jo prøve å fikse. 
Lesemodus:
Endringsmodus:
>  ✨Statustag på vedtaksperioder

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/VedtakOgBeregningBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/VedtakOgBeregningLæremidler.tsx
- src/frontend/typer/vedtak/vedtakLæremidler.ts
- src/frontend/typer/vedtak/vedtakTilsynBarn.ts
- Hvis man i en revurdering først setter avslag og sen innvilgelse er det ønskelig å ikke sende med et typcastet avslag videre til innvilgelseskomponenten, men at man faktiskt henter forrige vedtak sånn at man får gjenbrukt perioder fra forrige behandling
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24180
Et alternativ er å gjøre en hjelpemetode
```typescript
export const vedtakHvisType = <VEDTAK extends VedtakResponse, RESULT extends VEDTAK>(
vedtak: VEDTAK,
typechecker: (vedtak: VEDTAK) => vedtak is RESULT
): RESULT | undefined => {
if (typechecker(vedtak)) {
return vedtak;
}
return undefined;
};
// og bruke som
{typeVedtak === TypeVedtak.INNVILGELSE && (
<InnvilgelseLæremidlerEllerVedtaksperioderFraForrigeBehandling …
```
> Skal gjenbruke forrige vedtak hvis riktig type, i stedet for å typecaste

- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgeLæremidler.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/VedtaksperiodeRad.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/Vedtaksperioder.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/validering.ts
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/vedtakLæremidlerUtils.ts
- src/frontend/hooks/useMapById.ts
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24129
* Det var tidligere mulig å sette datoet før revurder fra og de ble då låste
* Dette er løst med at perioder blir låste i forhold til perioden for den opprinnelige perioden var. På lik måte som det gjøres i stønadsperioder idag
* Lagt til at man validerer fom/tom mot revurder fra
> Vedtaksperiode læremidler endre dato før revurder-fra

- src/frontend/Sider/Behandling/Brev/Brev.tsx
- src/frontend/komponenter/Brev/Brevknapp.tsx
- src/frontend/komponenter/Brev/Brevmeny.tsx
I PR #694 bruktes `useTotrinnskontroll` utenfor provideren fordi brevknapp både brukes i behandling og frittstående brev. Har nå flyttet dette lenger ut slik at brevknappen i frittstående brev ikke trigger feilmelding.
> Skal sjekke totrinnstatus innenfor provideren til contexten

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsynV2.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/VedtaksperiodeRad.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Vedtaksperioder.tsx
- src/frontend/typer/vedtak/vedtakTilsynBarn.ts
Det var tidligere mulig å sette datoen for fom/tom før revurder fra som gjorde at datofeltene ble låst
Samme som ble gjort for læremidler her: https://github.com/navikt/tilleggsstonader-sak-frontend/pull/697
> 🦺 Skal ikke låse felter når man endrer fom/tom før revurder fra dato

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeVilkår.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreTypeOgDatoer.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/målgruppe.ts
Lagt til "Gjenlevende - gammelt regelverk" som en målgruppe som er mulig å velge når man legger til målgruppe, men valg av denne trigger en alert og det er ikke mulig å lagre.
> Skal vise alert om at gjenlevende etter gammelt regelverk ikke støttes

- src/frontend/Sider/Admin/Oppfølging/KontrollerOppfølging.tsx
- src/frontend/Sider/Behandling/Brev/useSendTilBeslutter.ts
- src/frontend/Sider/Behandling/Fanemeny/UtenBrev.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetBarnetilsyn.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetLæremidler.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/OppdaterGrunnlag/OppdaterGrunnlagKnapp.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/OppdaterGrunnlag/useOppdaterGrunnlag.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/SlettVilkårperiodeModal.tsx
- src/frontend/Sider/Behandling/RevurderFra/RevurderFra.tsx
- src/frontend/Sider/Behandling/SettPåVent/SettPåVentForm.tsx
- src/frontend/Sider/Behandling/SettPåVent/TaAvVentModal.tsx
- src/frontend/Sider/EksternOmruting/EksternOmrutingBehandling.tsx
- src/frontend/Sider/EksternOmruting/EksternOmrutingSaksoversikt.tsx
- src/frontend/Sider/Journalføring/Standard/Journalføring.tsx
- src/frontend/Sider/Oppgavebenk/Oppgavebenk.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettKlageBehandling.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettOrdinærBehandling.tsx
- src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaveliste.tsx
- src/frontend/context/InngangsvilkårContext.ts
- src/frontend/komponenter/Brev/Brevknapp.tsx
- src/frontend/komponenter/DataViewer.tsx
- src/frontend/komponenter/Feil/Feilmelding.tsx
- src/frontend/komponenter/Feil/feilmeldingUtils.ts
- src/frontend/komponenter/Stegflyt/StegKnapp.tsx
- src/frontend/typer/ressurs.ts
[Favro-kort](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24221)
Har endret på `<Feilmelding/>` slik at den enten kun tar inn en feil av følgende typer: 
- `undefined` - returnerer null (som før)
- `string` - returnerer teksten i en alert av typen "warning" (oransje) fordi denne brukes dersom man vil kaste en feil i frontend. Disse feilene er gjerne noe saksbehandler kan rette opp i selv og da trenger de ikke være så dramatisk.
- , `Feil` - Denne returnerer en litt mer strukturert feilmelding hvor feilkoden er mindre og hele feilmeldingen kan kopieres.
Hvis man trenger å sende inn en string, men ønsker å ha error (rød) feilmelding så kan bruke funksjonen `lagFeilmelding()` og sende med statusen `RessursStatus.Feilet`.
Se commit for commit!!! ⚠️ …
> Visning av feilmeldinger

- src/frontend/Sider/Klage/Steg/Formkrav/EndreFormkravVurderinger.tsx
- src/frontend/Sider/Klage/Steg/Vurdering/HjemmelVelger.tsx
- src/frontend/Sider/Klage/Steg/Vurdering/Vedtak.tsx
- src/frontend/Sider/Klage/Steg/Vurdering/Vurdering.tsx
- src/frontend/Sider/Klage/Steg/Vurdering/VurderingLesemodus.tsx
- src/frontend/Sider/Klage/Steg/Vurdering/vurderingsfelter.ts
- src/frontend/Sider/Klage/hooks/useVurdering.ts
Det er ønskelig å kunne velge flere hjemler ved oppretthold vurdering
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21506
* https://github.com/navikt/tilleggsstonader-klage/pull/68
> Støtte for å kunne legge inn flere hjemler ved oppretthold vurdering

- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/aktivitetBarnetilsyn.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/aktivitetLæremidler.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/målgruppe.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/vilkårperiode.ts
- src/frontend/Sider/Behandling/OppsummeringVilkår/OppsummeringVilkårperioder.tsx
- src/frontend/Sider/Behandling/OppsummeringVilkår/OppsummeringVilkårperioderOgVilkår.tsx
- src/frontend/Sider/Behandling/OppsummeringVilkår/VilkårOppsummeringRad.tsx
- src/frontend/Sider/Behandling/Stønadsvilkår/Stønadsvilkår.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsynV2.tsx
Flytter og bryter ut oppsummering av vilkår på vedtakssiden for tilsyn barn for å kunne gjenbruke på fanen for stønadsvilkår
Legger den ikke bak feature toggle då den kan vises før vi legger ut dette i prod
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24497
> Oppsummering vilkår i fanen for stønadsvilkår

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/BrukAktivitetKnapp.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsAktivitet.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/RegisterYtelserTabell.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/utils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/vilkårperiodeUtil.ts
I [pr 613 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/613) blir det lagt inn at man henter aktiviteter og ytelser helt fra første registrerte vilkårperiode. Da man ikke vil kunne lagre ned vilkårsperioder som starter før revurder fra er det dumt å gi de tilbudet. 
Knappen fjernes nå dersom man revurderer etter at en aktivitet eller ytelse er ferdig. Dvs. at man kan bruke en periode hvis man revurderer midt i perioden, men man vil ikke kunne lagre ned med mindre man endrer på "fom" datoen. Dette gjør at man kan beholde kildeId-en på aktiviteter fremfor å manuelt legge inn uten denne koblingen
> Skal ikke vise bruk-knapp på aktiviteter/ytelser som slutter før revurder fra dato

- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/Beregningsresultat.tsx
- src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabellLæremidler.ts
- src/frontend/typer/vedtak/vedtakLæremidler.ts
> Gitt at jeg står i en revurdering av Læremidler
> Når jeg reberegner en periode som allerede er utbetalt
> Så skal jeg på vedtak og beregningssiden få et varsel om at den beregnede perioden treffer en allerede utbetalt måned
Når man revurderer og legger til en periode i en allerede løpende måned så er det ønskelig å markere den måneden at det er en del av en allerede utbetalt måned. Den skal markeres for å gjøre det tydelig og at man i vedtaksbrevet skal kunne skrive en tekst om endringen.
* Uendret beløp
* Lavere beløp
* Høyere beløp
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24527
* https://github.com/navikt/tilleggsstonader-sak/pull/621
> Læremidler vedtaksperioder revurdering tidligere perioder

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/AktivitetKortLesevisning/AktivitetKort.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/AktivitetKortLesevisning/AktivitetKortFooter.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/AktivitetKortLesevisning/AktivitetUlikRegisterVarsel.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/AktivitetKortLesevisning/UlikheterVarselAktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/AktivitetKortLesevisning/aktivitetKortUtils.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/BrukAktivitetKnapp.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/RegisterAktivteterTabell.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsAktivitet.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/OppsummertVilkårsvurdering.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/VilkårperiodeKortBase.tsx
Hjelpe SB og beslutter å se ulikheter mellom aktivitet i arena og lagt til i TS-sak. 
Skjules dersom behandlingen er ferdigstilt slik at man ikke viser noe på gamle behandlinger som SB ikke så da saken ble behandlet. Gjøres nå i frontend fordi det var raskeste vei til mål. En mulig videreutvikling er å ha mer detaljer om det er SB som har endret det eller om det er arena som er oppdatert, men dette bør lagres ned
Vise tag med "forskjell" fra arena aktivitet og aktivitetid dersom den er brukt: 
Vise id-en til aktiviteten i tabellen, som tag hvis den er brukt slik at den matcher det som er på kortet:
> Marker endring og vis aktivitetid

- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår.tsx
- src/frontend/komponenter/Skjema/MånedÅrVelger/MånedVelger.tsx
- src/frontend/komponenter/Skjema/MånedÅrVelger/MånedÅrVelger.tsx
- src/frontend/komponenter/Skjema/MånedÅrVelger/ÅrVelger.tsx
- src/frontend/utils/toggles.ts
Teste ut å velge dato for utgifter med dropdowns for å gjøre det tydligere at det er snakk om hele måneder og ikke spesifikke datoer. Brukes kun dersom toggle er på for at Tone+flere skal få teste det før vi faktisk går for dette.
⚠️ Har ikke gjort spesielt mye tilpasninger annet enn å kopiere fra EF fordi det ikke er sikkert at vi ønsker å beholde dette. Første commit er ren kopi, resten er et par tilpasninger for at stylingen skal matche det vi har ellers. Kan være ting som er kopiert med som ikke er nødvendig.
> ✨ Ta i bruk måned-år velger som dropdown på utgifter

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Delvilkår/AktivitetDelvilkårBoutgifter.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitet.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetBoutgifter.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsBoutgifter.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/valideringAktivitetBoutgifter.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/aktivitet.ts
- src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/aktivitetBoutgifter.ts
Ønsker å kunne velge aktivitet i inngangsvilkår for boutgifter
Nesten en blåkopi av tilsyn barn. 
- Har fjernet "reel arbeidssøker" som mulig aktivitet. 
- Beholder "aktivitetsdager" da det ikke er landet om dette skal med
- Kunne laget mere generelle komponenter som går på tvers av tilsyn barn og boutgifter, men velger å kopiere for å gjøre oss mere fleksible på endringer i den ene stønaden uten at det trenger å påvirke den andre
> ✨ Legg til muligheten for å velge aktivitet i inngangsvilkår for boutgifter

- src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx
Ønsker å kunne legge inn målgruppe for boutgifter
> ✨ Legg til målgruppe for boutgifter

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/utils.ts
- src/frontend/typer/vedtak/vedtakTilsynBarn.ts
Rydd opp etter overgang til vedtaksperioder for tilsyn barn. Renamer `InnvilgelseTilsynBarnRequestV2` til `InnvilgelseTilsynBarnRequest` og fjerner gammel `InnvilgelseTilsynBarnRequest`.
> Fjern InnvilgelseTilsynBarnRequestV2

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
Rydder opp etter migreringen til vedtaksperioder. Målet er å kunne fjerne V2 endepunktene fra backend. `/innvilgelse` og `/innvilgelseV2` har nå samme logikk backend. `/beregn` og `/beregnV2` har også samme logikk backend.
> ♻️ Fjern "V2" fra endepunktene for beregn og innvilgelse tilsyn barn

- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/NyttVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/tekster.ts
- src/frontend/Sider/Behandling/vilkår.ts
Ønsker ulike tekster for "utgift" for de ulike vilkårene. For faste boutgifter er det viktig å presisere at det er merutgifter. 
Pass barn:
Midlertidig utgift:
Fate utgifter:
> Tekster for utgift

- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/LesevisningFremtidigUtgift.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/LesevisningVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/validering.ts
- src/frontend/Sider/Behandling/vilkår.ts
Ønsker å kunne lagre et vilkår som "fremtidig utgift" der vilkårsvurderingene ikke er gjort.
Ligger bak feature toggle til det er funksjonelt avklart i hvilke tilfeller dette skal brukes
> Fremtidig utgift

- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/NyttVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx
Skal ikke kunne gjøre et vilkårsvurdert vilkår til fremtidig utgift i en revurdering. Dette ville vært en rar endring. 
Bildet viser fremtidig utgift som kan bli til vanlig vilkår
Bildet viser vilkårsvurdert vilkår der switch for å gjøre vilkåret om til fremtidig utgift er fjernet
> Skal ikke kunne gjore et vilkårsvurdert vilkår til fremtidig utgift

- src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx
Skal alltid kunne slette vilkår som er fremtidig utgift. Dette trengs hvis en fremtidig utgift ikke taes i bruk.
⚠️ Lager PR mest for å vente på denne https://github.com/navikt/tilleggsstonader-sak/pull/698
> 👔 Alltid vis slett-vilkår knappen hvis vilkår er fremtidig utgift

- src/frontend/hooks/useBehandlingOppsummering.ts
Tidligere ble oppsummeringen kun lastet inn ved steg-bytte, men det gjorde at den feks ikke ble lastet inn på nytt ved endring av revurderFra-dato
> Skal laste inn oppsummeringen ved fanebytte

- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår/EndreDelvilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår/EndreErFremtidigUtgift.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår/EndrePeriodeForVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår/EndreUtgift.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår/EndreVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/NyttVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx
Deler opp `EndreVilkår` til:
- `EndrePeriodeForVilkår`
- `EndreErFremtidigUtgift`
- `EndreUtgift`
- `EndreDelvilkår`
Målet et at filene skal bli mindre så det er lettere å sette seg inn i og gjøre endringer. 
⚠️ Dette er kun refaktorering. Det skal ikke være noen funksjonelle endringer her
ℹ️ Samme endring som i https://github.com/navikt/tilleggsstonader-sak-frontend/pull/750, men siden den ble henge så langt bak klarte jeg ikke å merge inn main på noen fornuftig måte
> ♻️ Del EndreVilkår til flere mindre filer

- src/frontend/Sider/Behandling/VedtakOgBeregning/Boutgifter/innvilgeVedtak/BeregningsresultatContainer.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Boutgifter/innvilgeVedtak/BeregningsresultatMedUtgift.tsx
- src/frontend/komponenter/Brev/Brevmeny.tsx
- src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabell.ts
- src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabellBoutgifter.ts
- src/frontend/typer/vedtak/vedtakBoutgifter.ts
Ønsker at det skal være tydlig for brukeren hvor mye hen får utbetalt per samling.
Har oppdatert utbetalingstabellen i brevet slik at den viser alle utgifter og hvor stor andel av utgiften som blir utbetalt.
> Utbetaling tabell i brev

- src/frontend/Sider/Personoversikt/Behandlingsoversikt/Arena/VedtaksoversiktArena.tsx
- src/frontend/Sider/Personoversikt/PersonoversiktInnhold.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/DetaljertVedtaksperiodeRadBoutgifter.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/OversiktKort.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversikt.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktArena.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktBoutgifter.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktLæremidler.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktTilsynBarn.tsx
- src/frontend/hooks/useHentFullstendigVedtaksOversikt.tsx
- src/frontend/typer/vedtak/vedtakBoutgifter.ts
- src/frontend/typer/vedtak/vedtaksperiodeOppsummering.ts
- src/frontend/utils/toggles.ts
- Legger til tab for vedtaksperioder. 
- Fjerner TS-Arena tab
- Re-namer Ytelser -> Andre ytelser
**Alt ligger bak bryter.**
_Note:
Dersom det er overnatting vil fom og tom være perioden for utgiften._
**Vedtaksperioder alle stønader:**
**Oversikt over boutgifter overnatting:**
Dersom bryteren er av ser det slik ut:
> ✨Vedtaksperioder paa personoversikt

- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Boutgifter/innvilgeVedtak/InnvilgeBoutgifter.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Felles/StegKnappInnvilgelseMedVarselOmVedtakIArena.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgeLæremidler.tsx
- src/frontend/komponenter/Stegflyt/StegKnapp.tsx
- src/frontend/komponenter/Stegflyt/StegKnappBekreftelsesModal.tsx
Hvis man har et vedtaksperioder som begynner før vedtak i Arena slutter så er det ønskelig med en bekreftelsesmodal for saksbehandler.
Modalen er lagt til i `StegKnapp` for å kunne håndtere `gåTilNesteSteg` i `StegKnapp` som gjør diverse saker. 
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24238
> Varsel vedtaksperiode før arena vedtak

- src/frontend/Sider/Behandling/Simulering/SimuleringResultatWrapper.tsx
Endrer titelen til å vise måned og år for å tydeliggjøre at:
- Simuleringen kan gå over flere år
- Hindre forvirring dersom man simulerer fra en dato som er midt i en måned.
**Ny titel**
[Oppgave i favro](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-25226)
> Viser mnd og år for simulering

- src/frontend/Sider/Behandling/Totrinnskontroll/FatteVedtak.tsx
- src/frontend/komponenter/Feil/Feilmelding.tsx
Liten fiks på at man alltid viser knappen for fullfør på totrinnskontroll når man underkjenner. 
Skjemaet har også fått feltvalidering for å hindre at man sender inn tom årsak og begrunnelse. 
[Oppgave i Favro](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-25116)
**Før:**
**Etter:**
**Feltvalidering**
**Feilmelding fra back-end**
> Viser alltid knappen for fullfør på underkjennelse, med feltvalidering

- src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/FagsakOversikt.tsx
- src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettNyBehandlingModal.tsx
Småfiks på luft mellom tabeller og størrelse på knapper i sak fanen på personoversikten.
[Oppgave i Favro](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-25291)
[Skisser i figma](https://www.figma.com/design/7eVA9o9YdfQi7MRuzx9wWu/TS-sak--Personoversikt?node-id=115-1469&m=dev)
**Etter:**
> Endrer på luft og størrelse på knapper

- src/frontend/Sider/Behandling/Vilkårvurdering/DelvilkårRadioknapper.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår/EndreErFremtidigUtgift.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår/EndreUtgift.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/tekster.ts
Ønsker at det skal bli lettere for saksbehandler å gjøre vurderingen.
- lagt til "Slik gjør du vurderingen" 
- lagt til hjelpetekst på merugfiter
- oppdatert spørsmålstekst på overnatting
"Slik gjør du vurderingen" eksempel: 
Hjelpetekst merutgift eksempel:
> Hjelpetekster boutgifter

- src/frontend/komponenter/Brev/Brevmeny.tsx
- src/frontend/komponenter/Brev/punktliste/lagInnvilgetPerioderPunktliste.ts
- src/frontend/komponenter/Brev/variablerUtils.ts
- src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabell.ts
- src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabellBoutgifter.ts
- src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabellLæremidler.ts
- src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabellTilsynBarn.ts
Legger til muligheten til å legge inn en punktliste med datoer vedtaket innvilges for. Dette er for å tydeliggjøre eventuelle "hull" mellom første dato i første periode og siste dato i siste periode. 
Utkast fra eksempelbrev:
Det gjenstår å ta dette i bruk i eksisterende brev. Nå brukes den kun i et eksempelbrev
>  ✨ Puktliste for innvilget periode i brev

- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversikt.tsx
For å tydligere indikere at siden ikke har innhold. 
Tidligere viste bare en tom side dersom det ikke var data. Nå vil det alltid være en overskrift.
**Tom side**
**Side med innhold**
> Overskrift på vedtaksperioder

- src/frontend/komponenter/Feil/Feilmelding.tsx
Skal formatere feilmelding fra backend på en hyggeligere måte. 
Før:
Nå:
> 💄 Wrap feilmelding-tekster når bruker `\n` for ny linje

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx
- src/frontend/Sider/Behandling/Stønadsvilkår/Stønadsvilkår.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Beregningsresultat.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Boutgifter/innvilgeVedtak/Beregningsresultat.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/Beregningsresultat.tsx
- src/frontend/Sider/Behandling/faner.tsx
- src/frontend/context/StegContext.ts
- src/frontend/typer/vedtak/vedtakBoutgifter.ts
- src/frontend/typer/vedtak/vedtakLæremidler.ts
- src/frontend/typer/vedtak/vedtakTilsynBarn.ts
- src/frontend/utils/toggles.ts
- src/frontend/utils/unleashMock.ts
Revurder-fra fane skjules når `sak.utled-endringsdato-revurdering` er skrudd på.
Legger også til nytt felt `beregnetFra` på beregningsresultat for de forskjellige stønader, som viser datoen vedtaket er beregnet fra hvis det er en revurdering
https://github.com/navikt/tilleggsstonader-sak/pull/750
> Fjerner revurderFra-fane når vi utleder endringsdato automatisk

- src/frontend/Sider/Behandling/VedtakOgBeregning/Boutgifter/innvilgeVedtak/BeregningsresultatMedUtgift.tsx
- src/frontend/komponenter/Brev/punktliste/lagInnvilgetPerioderPunktliste.ts
- src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabellBoutgifter.ts
- src/frontend/typer/vedtak/vedtakBoutgifter.ts
Opprydding der vi tar i bruk `utgifter` på beregningsresultat for boutgifter slik at `utgifterTilUtbetaling` kan slettes i backend.
Er vidre jobbing på dette: https://github.com/navikt/tilleggsstonader-sak/pull/749
> ♻️ Rename `utgifterTilUtbetaling` -> `utgifter`

- src/frontend/Sider/Behandling/VedtakOgBeregning/Felles/Opphørsvedtak.tsx
- src/frontend/Sider/Behandling/VedtakOgBeregning/Felles/validering.ts
- src/frontend/Sider/Behandling/Venstremeny/BehandlingOppsummering/VedtakOppsummering.tsx
- src/frontend/hooks/useLagreOpphør.ts
- src/frontend/typer/behandling/behandlingOppsummering.ts
Backend: https://github.com/navikt/tilleggsstonader-sak/pull/756
Nytt felt ved opprettelse av vedtak `opphørsdato`, for å tilpasse ved fjerning av revurder-fra.
> La saksbehandler sette opphørsdato i vedtakssteg når man opphører et vedtak

- src/frontend/Sider/Personoversikt/Dokumentoversikt/Dokumentoversikt.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/IngenVedtaksperioderInfo.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversikt.tsx
- src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktArena.tsx
- src/frontend/hooks/useHentFullstendigVedtaksOversikt.tsx
Gjøre det tydligere at TS-sak funker når det ikke finnes data.
Hvis ingen vedtaksperioder:
Hvis ingen dokumenter så vises oppdatert tidspunkt:
(La også til oppdatert tidspunkt på vedtaksperioder)
> Tydliggjør ingen data i vedtaksperioder- og dokumentoversikt-fane

- src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx
- src/frontend/Sider/Behandling/Felles/VarselRevurderFraDatoMangler.tsx
Forberedelse for testing av fjerning av revurder-fra. Fjerner revurder-fra fanen og viser et varsel (tar gjerne forbedringsforslag på teksten..) om man er i en revurdering i lesemodus hvor revurder-fra ikke er satt. 
Dette for å gi tydelig varsel til beslutter om at denne behandlingen har blitt brukt til å teste ny funksjonalitet.
> Gjemme revurder-fra fane og vis varsel om testing uten revurder-fra

- src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/BrukAktivitetKnapp.tsx
- src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/vilkårperiodeUtil.ts
Utdanning er ikke en relevant aktivitet for Daglig Reise Tsr. Skjuler derfor 'bruk'-knappen slik at SB ikke bruker aktiviteter av typen utdanning.
> 👔 Skjul 'bruk'-knapp for utdanning for Daglig Reise Tsr

- src/frontend/Sider/Behandling/Stønadsvilkår/DagligReise/LesevisningVilkårDagligReise.tsx
- src/frontend/Sider/Behandling/Venstremeny/BehandlingOppsummering/OppsummeringVilkår.tsx
- src/frontend/Sider/Behandling/Vilkårvurdering/tekster.ts
Oppdaterer **_"oppsummeringen av vurderingen"_** for å vise hvilke type daglig reise som er aktuell for perioden. 
[Oppgave i favro](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-26190)
En reise:
Flere reiseperioder:
> Tilpasser oppsummering av vurdering for offentlig transport
