src/backend/logger.ts, src/backend/miljø.ts, src/backend/package.json, src/backend/server.ts, src/backend/yarn.lock
@blommish tok utgangspunkt i det du hadde lagt til i søknaden 🤠
=> Logging 🔬 

.gitignore
=> Lagt til .gradle i gitignore

webpack/webpack.production.js
https://tilleggsstonader.intern.dev.nav.no/person/123/behandlinger
=> Endret public path til / for å kunne få /person/123 til å virke

.nais/dev.yaml, .nais/prod.yaml, .prettierignore, src/backend/auth/attachToken.ts, src/backend/auth/client.ts, src/backend/auth/inMemoryCache.ts, src/backend/auth/secondsUntil.ts, src/backend/miljø.ts, src/backend/package.json, src/backend/proxy.ts, src/backend/server.ts, src/backend/webpack/webpack.development.ts, src/backend/yarn.lock
Inspirasjon fra https://github.com/navikt/dp-auth og familie-felles-frontend/auth
=> Oppsett for Azure og obo token

src/backend/auth/client.ts, src/backend/miljø.ts, src/backend/package.json
=> Config for å kunne kjøre mot preprod fra lokalt

src/frontend/App.tsx, src/frontend/Sider/Oppgavebenk/Oppgavebenk.tsx, src/frontend/Sider/Oppgavebenk/OpprettDummyBehandling.tsx, src/frontend/utils/miljø.ts
Ønsker å kunne opprette dummybehandling for testing under utvikling
[Favrooppgave](https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-15551)
=> ✨  Opprett dummy behandling

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeVedtak.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/UtgiftsperiodeValg.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/vedtaksvalidering.ts, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/VedtakOgBeregningBarnetilsyn.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/utils.ts, src/frontend/Sider/Behandling/VedtakOgBeregning/Felles/utils.ts, src/frontend/hooks/felles/useFieldState.ts, src/frontend/hooks/felles/useFormState.ts, src/frontend/hooks/felles/useListState.ts, src/frontend/typer/vedtak.ts, src/frontend/utils/tall.ts
Trenger litt filer for å kunne innvilge vedtak. Nå har jeg tatt ren kopi av hooks for å håndtere forms. Og lagt inn delkopier av filene som har med innvilgelse å gjøre. All funksjonalitet og felter er tatt vekk og tas inn i egen PR.
=> ✨ Initielt oppsett av innvilge vedtak komponenter

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/AktivitetSelect.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/AntallDagerSelect.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/PeriodetypeSelect.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/UtgiftsperiodeValg.tsx, src/frontend/komponenter/Skjema/DateInput.tsx, src/frontend/komponenter/Skjema/Lesefelt.tsx, src/frontend/utils/dato.ts
Skal legge inn felter hvor man kan sette verdiene som er nødvendige for en utgiftsperiode: 
**OBS:**
- Commit for commit burde være relativt ryddig
- Valgt å bruke samme komponent for både `antallAktivitetsdager` og `dagerMedPass` fordi de ble såpass like
- Placeholders for velge barn og utgifter
Kommer senere: 
- Å velge barn + utgifter kommer 
- Sjekke om oppdatering av state faktisk fungerer
- Feilmelding og validering
- Styling
=> Beregning utgiftsperioder

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/UtgiftsperiodeValg.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgiftsperiode/VelgBarn.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/vedtaksvalidering.ts, src/frontend/komponenter/Skjema/DateInput.tsx, src/frontend/utils/dato.ts
Trenger validering av alle felter for en utgiftsperiode.
Foreløpig ganske simpel validering av at felter er satt. Må nok legge til mer her når vår får mer info, f.eks. validere felter mot hverandre osv.  
**Les commit for commit**
=> ✨ Utgiftsperioder validering

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx, src/frontend/Sider/Behandling/vilkår.ts, src/frontend/hooks/useRegler.ts, src/frontend/typer/regel.ts
En start på vilkårsvurdering, neste steg er å vise frem vurderingsknappene/logikken 😎
=> ✨ Skal hente regler fra backend

src/frontend/hooks/useRegler.ts
* https://github.com/navikt/tilleggsstonader-sak/pull/40
=> Endepunkt vurdering -> vilkar

src/frontend/utils/fetch.ts
Vil hente data fra endepunkter som ikke returnerer json, f.eks. bytearray for pdf.
=> ✨ Skal håndtere fetch som ikke returnerer json, f.eks. blob

src/frontend/Sider/Behandling/Brev/Delmal.tsx, src/frontend/Sider/Behandling/Brev/DelmalMeny.tsx, src/frontend/Sider/Behandling/Brev/Fritekst.tsx, src/frontend/Sider/Behandling/Brev/Sanity/ValgfeltSerializer.tsx, src/frontend/Sider/Behandling/Brev/Sanity/queries.ts, src/frontend/Sider/Behandling/Brev/Valgfelt.tsx, src/frontend/Sider/Behandling/Brev/typer.ts
Innhold fra fritekstavsnitt skal vises i det genererte brevet
=> ✨  Fritekstavsnitt brev

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Stønadsperiode/StønadsperiodeValg.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/Utgifter.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
Skal lagre ned endringer som skjer i feltene fra PR #67 i `FormState`.
Fjernet også overflødige typer som har blitt med i funksjonene ved kopiering 🤠
=> Skal oppdatere formstate ved oppdatering av felter

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Stønadsperiode/StønadsperiodeValg.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx
Skal være mulig å lagre ned innvilget vedtak ([favro](https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16181))
=> Send vedtak til backend for lagring etter vellykket validering

src/frontend/komponenter/Modal/ModalWrapper.tsx
Kopiert inn ModalWrapper for å få en felles måte å håndtere modals på
Den er kopiert inn fra ef-frontend uten noen endringer
Dette er ju sannsynligvis noe som kommer få endringer senere, men tenker vi kan kopiere inn den as is nå, og senere vurdere om vi trenger noe annet.
=> Lagt til ModalWrapper

src/frontend/Sider/Oppgavebenk/Oppgavebenk.tsx, src/frontend/Sider/Oppgavebenk/Oppgaverad.tsx, src/frontend/Sider/Oppgavebenk/Oppgavetabell.tsx, src/frontend/Sider/Oppgavebenk/OpprettDummyBehandling.tsx, src/frontend/Sider/Oppgavebenk/typer/enhet.ts, src/frontend/Sider/Oppgavebenk/typer/oppgave.ts, src/frontend/Sider/Oppgavebenk/typer/oppgavetema.ts, src/frontend/context/OppgaveContext.ts, src/frontend/hooks/felles/usePaginerState.ts, src/frontend/hooks/felles/useSorteringState.ts, src/frontend/komponenter/Feil/Feilmelding.tsx, src/frontend/utils/dato.ts
https://github.com/navikt/tilleggsstonader-sak-frontend/pull/75 er splittet i 3 PR'er, denne og
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/82
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/83
https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16288
For mer detaljer av hva som har skjedd: https://github.com/navikt/tilleggsstonader-sak-frontend/compare/oppgavebenk
=> Henting og visning av tabell av oppgaver

src/frontend/Sider/Oppgavebenk/Oppgavebenk.tsx, src/frontend/Sider/Oppgavebenk/filter/Oppgavefiltrering.tsx, src/frontend/Sider/Oppgavebenk/filter/SaksbehandlerVelger.tsx, src/frontend/Sider/Oppgavebenk/filter/filterutils.ts, src/frontend/Sider/Oppgavebenk/filter/oppgavefilterStorage.ts
https://github.com/navikt/tilleggsstonader-sak-frontend/pull/75 er splittet i 3 PR'er, denne og
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/81
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/82
https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-16288
For mer detaljer av hva som har skjedd: https://github.com/navikt/tilleggsstonader-sak-frontend/compare/oppgavebenk
=> Oppgave filtrering

src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/PassBarn/PassBarn.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/VurderDelvilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/tekster.ts, src/frontend/Sider/Behandling/vilkår.ts
Skal kunne vurdere div info om pass for hvert barn: 
Har også gjort: 
- Tekster er ordentlige tekster og ikke bare ID-er. Dette kunne vært en egen PR, men siden jeg antar at ordlyden uansett må sjekkes av andre er det ikke så viktig å se nøye her
- Gjorde radio-knappene small fordi det ble så mye
**OBS**
Det er ikke sikkert alt skal ligge på samme side, men vi tester dette for nå
=> Vilkår for pass av barn

src/frontend/Sider/Behandling/Inngangsvilkår/PassBarn/PassBarn.tsx, src/frontend/Sider/Behandling/Vilkårspanel/Informasjonsrad.tsx, src/frontend/Sider/Behandling/Vilkårspanel/VilkårpanelInnhold.tsx
Ble irritert av disse under utvikling, men de passet ikke inn i andre PR-er 🤠 
Se forklaring i commit-melding
=> 🐛 Fikset noen console warning/errors

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/FyllUtVilkårKnapp.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx, src/frontend/Sider/Behandling/Vilkårspanel/Vilkårpanel.tsx
Det er smud å trykke på en knapp for å fylle ut alle vilkår til testing💥 😎 
Henger sammen med [PR 91](https://github.com/navikt/tilleggsstonader-sak/pull/91) i backend
=> ✨ Automatisk utfylle vilkår

src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingOversikt.tsx, src/frontend/typer/fagsak.ts
I PR #103 glemte jeg å oppdatere at fagsaken heter `tilsynBarn` og ikke `barnetilsyn`
=> ♻️ Fagsak heter tilsynBarn

src/frontend/Sider/Behandling/Brev/Brevmeny.tsx, src/frontend/Sider/Behandling/Brev/Html.tsx, src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingOversikt.tsx, src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrev.tsx, src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrevFane.tsx, src/frontend/Sider/Personoversikt/PersonoversiktInnhold.tsx, src/frontend/hooks/useFagsakPerson.ts, src/frontend/typer/fagsak.ts
SB skal kunne sende brev utenfor en behandling. Et slikt brev skal være knyttet til en fagsak, og SB må derfor først velge hvilken fagsak man ønsker å lage brev for.
**Relevante PR-er i backend:**
- Hente fagsakId-ene som eksisterer på bruker: [PR 107](https://github.com/navikt/tilleggsstonader-sak/pull/107)
- Generere PDF: [PR 108](https://github.com/navikt/tilleggsstonader-sak/pull/108)
Commit for commit bør være smud
PS. Design er ikke gjort noe med
=> Frittstående brev - velg fagsak og generer pdf

src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
Ikke nødvendig, men kanskje ryddigere?
=> ♻️ Trekk ut stønadsperioderad som en egen komponent

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/LeggTilMålgruppe.tsx
Og fikset at man har tilgang til å skrive til packages som trengs, men som ble fjernet i https://github.com/navikt/tilleggsstonader-sak-frontend/pull/131/files av uhell
=> Fikset feil med nullstill målgruppe tom

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/LeggTilAktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/LeggTilMålgruppe.tsx
Ønsker å kunne avbryte og lukke visning av legg til periode
https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-17406
=> Skal kunne avbryte legg til periode

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/LeggTilAktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/validering.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/LeggTilMålgruppe.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/validering.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/validering.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer.ts, src/frontend/utils/dato.ts, src/frontend/utils/features.ts, src/frontend/utils/periode.ts
https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-17406
=> Skal validere at ny målgruppe og aktivitet er gyldig

src/frontend/Sider/Behandling/Brev/useMellomlagrignBrev.ts, src/frontend/Sider/Behandling/Brev/useMellomlagringFrittståendeBrev.ts, src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrev.tsx
=> Hent mellomlagret frittstående brev etter valg av fagsak

src/frontend/Sider/Behandling/Brev/useBrev.ts, src/frontend/Sider/Behandling/Brev/useMellomlagringFrittståendeBrev.ts, src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrev.tsx
=> Nullstill brev etter suksessfull sending

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/vedtaksvalidering.ts, src/frontend/utils/dato.ts, src/frontend/utils/periode.ts
Det ble feil i flytt av kode i tidligere PR 🛠️ 
https://github.com/navikt/tilleggsstonader-sak-frontend/pull/134/files#diff-103dd4f288f434a7c6f4f02a8dc45152c13f4e20ea1d5e6e7712f51c54b9c0cbL35
=> Fikset validering av tom >= fom av periode

src/frontend/Sider/Oppgavebenk/Oppgaverad.tsx, src/frontend/Sider/Oppgavebenk/Oppgavetabell.tsx
Work in progress, og designet er litt annerledes nå. Men prøver bare å dele opp i flere PRer 🤓 
Beskrivelse fjernes, og rekkefølge på gjenværende kolonner endres. Ihh til https://www.figma.com/file/T5lYk3vCOWiahrAs3jIaby/TILDE-~--Saksbehandling-pass-av-barn?type=design&node-id=4-317&mode=design&t=8qUKQ9xgeosOY2li-0
**Før** 📸 
**Etter** 📸
=> 🚧 Endre kolonner på oppgavebenk

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/LeggTilAktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/InngangsvilkårInnhold.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/LeggTilMålgruppe.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/validering.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer/aktivitet.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer/målgruppe.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer/stønadsperiode.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts, src/frontend/context/InngangsvilkårContext.ts
=> Inngangsvilkår nye typer

src/frontend/Sider/Behandling/Inngangsvilkår/InngangsvilkårInnhold.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/validering.ts, src/frontend/context/InngangsvilkårContext.ts
Lage switching mellom redigeringsmodus og visning. Kun en start, skal fortsette på å faktisk redigere og validere i egen PR
=> 🚧 Redigerbare felter i rad

src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/SlettVilkårperiodeModal.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts, src/frontend/komponenter/Ikoner/Vilkårsresultat/VilkårsresultatIkon.tsx, src/frontend/komponenter/Modal/ModalWrapper.tsx
Vilkårperioder skal kunne slettes.
Legger til knapp for sletting og visning av slettede perioder.
Kan leses commit for commit 👓 
**Ting jeg lurer på**
- Bør vi vise hvilken rad som slettes i modalen? Feks liste type og dato
- Bør vi begrense hvilke rader som kan slettes? Bør kanskje bare være de manuelle 🤔
=> ✨ Slett vilkårperiode

src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts, src/frontend/utils/dato.ts
Skal vise begrunnelse dersom den finnes.
=> ✨ Skal vise begrunnelse for vilkårperiode i lesevisning

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx
Går ikke å legge til ny aktivitet fordi den bruker feil endepunkt
=> 🐛 Bruk nytt endepunkt for å legge til vilkårperiode

src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx
Lager en v1 av #180 for å splitte ut delen hvor stønadsperioder blir gjort om til akseltabell
=> ♻️  Bytt ut grid med table for aksel

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts, src/frontend/context/InngangsvilkårContext.ts
Endring av vilkårsperioder kan gjøre stønadsperioder ugyldige. Dette skal derfor vises.
Henger sammen med https://github.com/navikt/tilleggsstonader-sak/pull/178
**Kan vurderes senere**
- Toast eller feilmelding ved vilkårsperiodene
=> ✨ Skal validere/vise stønadsperiodefeil ved endring av vilkårsperioder

src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx, src/frontend/Sider/Oppgavebenk/Oppgavebenk.tsx, src/frontend/Sider/Oppgavebenk/Oppgavetabell.tsx, src/frontend/Sider/Oppgavebenk/filter/Oppgavefiltrering.tsx, src/frontend/Sider/Oppgavebenk/filter/SaksbehandlerVelger.tsx, src/frontend/utils/miljø.ts
Har gjort noen småfix på oppgavebenken (spacing og gjør ting small) og skjult `Opprett dummy behandling` og `Automatisk oppfyll vilkår` midlertidig ikke-lokalt
Før: 
Etter:
=> 💄 Småfix demo - Oppgavebenk

src/frontend/Sider/Oppgavebenk/Oppgavebenk.tsx
=> Lag dummybehandling skal vises i preprod

README.md, src/frontend/Sider/Behandling/BehandlingInnhold.tsx
=> :bug: Fiks redirect til inngangsvilkår

README.md
=> Informer om bruk av copilot

src/frontend/Sider/Behandling/Inngangsvilkår/typer/aktivitet.ts
=> Fikser skrivefeil i "REEL_ARBEIDSSØKER"

src/frontend/App.tsx, src/frontend/komponenter/PersonHeader/PersonHeader.tsx, src/frontend/komponenter/PersonSøk.tsx, src/frontend/komponenter/Visningskomponenter/Sticky.ts
Se commits
https://favro.com/organization/98c34fb974ce445eac854de0/8a5276563da0f059dccd52a0?card=NAV-18309
=> 💄 Personheader søk

src/frontend/Sider/Behandling/Vilkårvurdering/EndreDelvilkår.tsx, src/frontend/komponenter/Skillelinje.tsx
=> Gjør skillelinje tilgjengelig for flere komponenter

src/frontend/Sider/Behandling/Stønadsvilkår/Stønadsvilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/DelvilkårRadioknapper.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/SlikGjørDuVurderingen.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/tekster.ts, src/frontend/komponenter/NesteStegKnapp/NesteStegKnapp.tsx, src/frontend/typer/regel.ts
- Endrer hjelpetekst på spørsmålene
- Endrer tekst på "Neste steg"-knapp
=> Tekster som matcher skissene

src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/SlettVilkårperiodeModal.tsx
Response for fjerning av støndsperiode er oppdatert Skal oppdatere stønadsperiodeFeil
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-18558
=> Fikset at fjernet vilkårperiode ikke blir oppdatert.

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx
Quickfix for å se valg av aktivitet under brukertest
Etter: 
Før:
=> 💄 Skal se hele select aktivitet i tabell

src/frontend/Sider/Behandling/Vilkårvurdering/LesevisningVilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx
Vilkår skal ikke kunne redigeres hvis behandlingen er ferdigstilt/på vent, eller steget er låst for redigering.
=> ✨ Lesevisning vilkår

src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeRad.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx, src/frontend/Sider/Behandling/faner.tsx, src/frontend/context/StegContext.ts, src/frontend/komponenter/NesteStegKnapp/NesteStegKnapp.tsx
Skal ikke kunne endre på inngangsvilkår hvis man ikke er i det steget.
=> ✨ Inngangsvilkår skal være i lesevisning dersom man ikke er i steg INNGANGSVILKÅR

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeRad.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx, src/frontend/context/StegContext.ts
Etter diskusjon på slack. https://nav-it.slack.com/archives/C05EKNFUXJ7/p1710770526947759
=> ♻️ Rename. stegErRedigerbar -> erStegRedigerbart

src/frontend/Sider/Oppgavebenk/Oppgaveknapp.tsx
Quickfix på label på behandlingsoppgaver. Etter ønske fra Marie.
=> ✨ Oppgaver knyttet til en behandling skal ha label "Behandle"

src/frontend/Sider/Journalføring/Standard/BrukerPanel.tsx, src/frontend/Sider/Journalføring/Standard/Journalføring.tsx, src/frontend/Sider/Journalføring/Standard/PanelHeader.tsx
Vent med å se gjennom denne til [denne PRen](https://github.com/navikt/tilleggsstonader-sak-frontend/pull/249) er godkjent og merget.
Følger:
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/249
Legger til et panel for visning av informasjon om bruker:
=> Journalføring brukerpanel

src/frontend/App.tsx, src/frontend/context/AppContext.ts
Ønsker å kunne logge ut sånn at jeg kan logge inn med annen saksbehandler
https://aksel.nav.no/komponenter/core/i-header#headerdemo-brukermeny
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20237
Når man trykker på logg ut vises "Sesjonen har utløpt. Prøv å last inn siden på nytt."
=> Skal kunne logge ut for å bytte til en annen saksbehandler

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Vedlegg.tsx, src/frontend/typer/behandling/behandlingFakta/faktaDokumentasjon.ts
Feltet skal ikke være med lenger
=> Fjerner "Vedlegg - har sendt inn tidligere" info-seksjon

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/ArbeidOgOpphold.tsx, src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Oppsummering.tsx, src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Visningskomponenter.tsx, src/frontend/typer/behandling/behandlingFakta/faktaHovedytelse.ts, src/frontend/typer/common.ts
Skal vise data som blir sendt inn i søknaden
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20247
Koblet til
* https://github.com/navikt/tilleggsstonader-sak/pull/251
=> ✨Opphold - Lagt til visning av fakta for arbeid og opphold

src/frontend/Sider/Journalføring/Standard/Journalføring.tsx
Når man fullfører manuell journalføring skal saksbehandler sendes til oppgavebenken, hvor man filterrer for brukeren man nettop har journalført for.
Kan også vurdere å implementere redirect til den nye opprettede behandlingen, men det er en forbedring vi kan ta senere.
=> ✨ Skal redirecte til oppagvebenk ved fullført journalføring

src/frontend/hooks/useHentBehandlinger.tsx, src/frontend/typer/behandling/behandling.ts
=> 🐛  Felt endret fra personIdent til ident i backend

src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/utils.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/OppsummertVilkårsvurdering.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/VilkårperiodeKortBase.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/tekstmapping.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/utils.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts
…ering
Tydliggjøre hva som mangler og ikke er oppfylt for SB:
**OBS:** er avhengig av [PR 278 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/278)!
=> Vilkåroppsummering

src/frontend/Sider/Behandling/Brev/Sanity/queries.ts, src/frontend/Sider/Behandling/Brev/useBrev.ts
De funksjonelle lager brev for avslag atm, og det er vanskelig å gjøre uten å kunne se resultatet i sak 😢
=> Skal midlertidig vise alle brev, ikke kun innvilgelse

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/AktivitetVilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utils.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/tekstmapping.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer/aktivitet.ts
Sykepenger skal bli egen målgruppe og ikke lenger være et delvilkår på aktitvitet.
Hører sammen med [PR 289 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/289)
=> Fjern sykepenger som delvilkår på aktivitet

src/frontend/Sider/Behandling/SettPåVent/SettPåVentInformasjon.tsx, src/frontend/Sider/Behandling/SettPåVent/typer.ts, src/frontend/utils/dato.ts
Se https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20785 
Hører sammen med https://github.com/navikt/tilleggsstonader-sak/pull/299
Nytt design:
=> "Sett på vent"-boksen skal vise datoen saken ble satt på vent

src/frontend/Sider/Behandling/Brev/Brev.tsx, src/frontend/Sider/Behandling/Brev/Brevmeny.tsx, src/frontend/Sider/Behandling/Brev/Delmal.tsx, src/frontend/Sider/Behandling/Brev/Valgfelt.tsx, src/frontend/Sider/Behandling/Brev/Variabler.tsx, src/frontend/Sider/Behandling/Brev/VelgBrevmal.tsx, src/frontend/Sider/Behandling/Totrinnskontroll/SendTilBeslutterKnapp.tsx, src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrev.tsx, src/frontend/Sider/Personoversikt/FrittståendeBrev/FrittståendeBrevFane.tsx, src/frontend/komponenter/PdfVisning.tsx
Et forsøk på å gjøre brevsidene litt ryddigere. 
Ingen funksjonelle endringer, bortsett fra at delmaler som ikke skal vises skjules i brevmeny
|Før|Etter|
|---|---|
|<img width="1722" alt="image" src="https://github.com/navikt/tilleggsstonader-sak-frontend/assets/46678893/2e85a9c4-c01c-4bb7-b5dc-083a55152643">|<img width="1722" alt="image" src="https://github.com/navikt/tilleggsstonader-sak-frontend/assets/46678893/70a0e423-a783-4da8-a67d-5ea5453f22c2">|
|<img width="1722" alt="image" src="https://github.com/navikt/tilleggsstonader-sak-frontend/assets/46678893/fb23c6c4-9a3d-43cd-9279-90e5b56e2e74">|<img width="1722" alt="image" src="https://github.com/navikt/tilleggsstonader-sak-frontend/assets/46678893/13d75dd8-f823-421d-95f9-8ad86ec7dd13">|
=> 💄 Opprydding av brevsider

src/frontend/Sider/Behandling/BehandlingContainer.tsx
=> 🐛 Hent fakta etter at behandling er hentet så grunnlagsdata kan opprettes

src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/RegisterAktivteter.tsx
Legger til visning av "Register aktiviteter", dvs aktiviteter hentet fra Arena.
På sikt skal disse brukes til automatisk populere skjema for saksbehandler, men denne funksjonaliteten er ikke implementert enda.
"LEGG TIL"-knappen er intill videre skjult i produksjon
****
****
=> Aktivitet på inngangsvilkaar del1

src/backend/proxy.ts
Vi bruker winston ellers vid logging 
https://logs.adeo.no/s/nav-logs-legacy/app/r/s/RdneB
=> Bruker winston-logger på nytt for å logge log-level

src/backend/miljø.ts, src/backend/server.ts, src/backend/webpack/webpack.development.ts
Antar klage-modulen i frontend skal kunne snakke direkte med klage-apiet uten å måtte gå via sak-api
=> Sett opp proxy mot klage-app

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utils.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/RegisterAktivteter.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts, src/frontend/context/InngangsvilkårContext.ts, src/frontend/hooks/useVilkårperioder.tsx
Saksbehandler skal kopiere innhold fra aktiviteter hentet fra arena til en ny vilkårsperiode.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20871
Avhengig av https://github.com/navikt/tilleggsstonader-sak/pull/329
Forbedringer senere:
- Fjerne legg til knapp i tabellen dersom en aktivitet er lagt til
- Filtrering på perioder/status
- Koble aktivitet sammen med vilkårsperioden?
=> ✨ MVP 1: Arenaaktiviteter inngangsvilkår

src/frontend/Sider/Personoversikt/Dokumentoversikt/Dokumentoversikt.tsx, src/frontend/typer/dokument.ts
Nå sendte vi ikke inn hva vi ønsket å hente, det resulterer i at alt hentes. Dette kan bli litt mye dokumenter å navigere seg mellom uten filtreringsmuligheter 😢
=> Skal kun hente dokumenter med tema TSO eller TSR

src/frontend/Sider/Behandling/Brev/useVerdierForBrev.ts, src/frontend/utils/dato.ts
=> ✨ Skal skrive ut dato i brev

src/backend/miljø.ts, src/frontend/Sider/Klage/App/hooks/useHentBehandling.ts, src/frontend/Sider/Klage/App/hooks/useHentBehandlingHistorikk.ts, src/frontend/Sider/Klage/App/hooks/useHentFagsystemVedtak.ts, src/frontend/Sider/Klage/App/hooks/useHentFormkravVilkår.ts, src/frontend/Sider/Klage/App/hooks/useHentPersonopplysninger.ts, src/frontend/Sider/Klage/App/hooks/useHentVurderinger.ts, src/frontend/Sider/Klage/Felles/Lenker/Lenker.ts, src/frontend/Sider/Klage/Komponenter/Behandling/BehandlingRoutes.tsx, src/frontend/Sider/Klage/Komponenter/Behandling/Brev/Brev.tsx, src/frontend/Sider/Klage/Komponenter/Behandling/Brev/OmgjørVedtak.tsx, src/frontend/Sider/Klage/Komponenter/Behandling/Brevmottakere/BrevMottakere.tsx, src/frontend/Sider/Klage/Komponenter/Behandling/Brevmottakere/BrevmottakereModal.tsx, src/frontend/Sider/Klage/Komponenter/Behandling/Brevmottakere/SøkOrganisasjon.tsx, src/frontend/Sider/Klage/Komponenter/Behandling/Brevmottakere/SøkPerson.tsx, src/frontend/Sider/Klage/Komponenter/Behandling/Henleggelse/HenleggModal.tsx, src/frontend/Sider/Klage/Komponenter/Behandling/Høyremeny/Dokumenter.tsx, src/frontend/Sider/Klage/Komponenter/Behandling/Vurdering/Vurdering.tsx, src/frontend/Sider/Klage/utils/utils.ts, src/frontend/Sider/Personoversikt/Behandlingsoversikt/FagsakOversikt.tsx, src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettNyBehandlingModal.tsx
Endringer gjort ifbm arbeid relatert til den nye "Klage"-behandlingen.
=> Sende klagesak til klage backend

src/frontend/Sider/Oppgavebenk/Oppgavetabell.tsx, src/frontend/Sider/Oppgavebenk/filter/Oppgavefiltrering.tsx, src/frontend/Sider/Oppgavebenk/filter/filterutils.ts, src/frontend/Sider/Oppgavebenk/filter/oppgavefilterStorage.ts, src/frontend/Sider/Oppgavebenk/oppgaverequestUtil.ts, src/frontend/Sider/Oppgavebenk/typer/oppgave.ts
Saksbehandler skal kunne finne oppgaver som er på vent.
Henger sammen med https://github.com/navikt/tilleggsstonader-sak/pull/339
=> ✨ Checkbox oppgaver på vent

.nais/dev.yaml, .nais/prod.yaml, package.json, src/backend/miljø.ts, src/backend/server.ts, src/backend/webpack/webpack.development.ts, src/frontend/App.tsx, webpack/webpack.production.js, yarn.lock
For å kunne informere saksbehandlerne om endringer
=> ✨ Endringslogg

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/RegisterAktivteter.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode.ts
=> Skal bruke tidspunkt hentet fra hentetInformasjon

src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/utils.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/utils.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/OppsummertVilkårsvurdering.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/typer/målgruppe.ts
Det er ønskelig med et nedtrekksvalg som tilsier at en person har 100% sykepenger som ikke gir rett på stønad i den perioden
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-20574
* https://github.com/navikt/tilleggsstonader-sak/pull/347
=> Lagt til målgruppe 100% sykepenger som ikke gir rett på stønadsperiode

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Utgifter/UtgifterValg.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/UtgifterLesMer.tsx
Det er ønskelig med mer informasjon om hvordan man skal legge til utgifter på vedtakssiden
=> Utgifter les mer

src/frontend/Sider/Personoversikt/Dokumentoversikt/DokumentRad.tsx, src/frontend/typer/dokument.ts
=> ✨ Vis tektslig versjon av tema istedenfor kode

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx, src/frontend/Sider/Behandling/Stønadsvilkår/PassBarn/PassBarn.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx, src/frontend/Sider/Behandling/lenker.ts, src/frontend/komponenter/VilkårPanel/VilkårPanel.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-21427
Aktivitet
Målgruppe
Pass barn
Beregning
=> Oppdatert lenker til paragrafer og lagt til forskrifter

.eslintrc, src/frontend/Sider/Behandling/Brev/Sanity/ValgfeltSerializer.tsx, src/frontend/Sider/Behandling/Brev/VariabelSerializer.tsx, src/frontend/komponenter/Feil/Feilmelding.tsx, src/frontend/komponenter/PdfVisning.tsx
Foreslår at vi legger til eslintregler for react, og då deres anbefalte oppsett.
https://github.com/jsx-eslint/eslint-plugin-react
Det hjelper med å få bedre logging ved feil, eks at komponenter har riktig navn etc.
Tok også å fikset feil som linten klagde på. 
Fortsettelse på
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/404
=> Forslag: Eslint react recommended settings

src/frontend/Sider/Personoversikt/Dokumentoversikt/Dokumentoversikt.tsx, src/frontend/utils/toggles.ts
=> 🗑️ Fjern toggle for filtrering i dokumentoversikt

src/frontend/Sider/Behandling/Venstremeny/Historikk/HendelseIkon.tsx, src/frontend/Sider/Behandling/Venstremeny/Historikk/Historikk.tsx, src/frontend/Sider/Behandling/Venstremeny/Historikk/HistorikkElement.tsx, src/frontend/Sider/Behandling/Venstremeny/Historikk/Metadata.tsx, src/frontend/Sider/Behandling/Venstremeny/Historikk/typer.tsx, src/frontend/Sider/Behandling/Venstremeny/Historikk/utils.ts, src/frontend/Sider/Behandling/Venstremeny/Venstremeny.tsx, src/frontend/utils/dato.ts, src/frontend/utils/toggles.ts
Visuell fremvisning av hva som har skjedd i en behandling og hvem som har gjort hva.
Har i utgangspunktet kun basert med på det som eksisterer, så
=> ✨ Visning av historikk på behandling v1

src/frontend/Sider/Oppgavebenk/Oppgaverad.tsx, src/frontend/Sider/Oppgavebenk/Oppgavetabell.tsx
Trengs for å sortere oppgaver på vent
PS: var ønskelig at dette ble vist uavhengig om "oppgaver på vent" er avhuket
=> ✨Vis frist på oppgave i oppgavebenk

src/frontend/Sider/Behandling/Venstremeny/Venstremeny.tsx, src/frontend/utils/toggles.ts
Toggle er skrudd på i prod og brukes. Ikke lenger nødvendig å ha
=> 🧼  Fjern toggling av behandlingshistorikk

src/frontend/Sider/Klage/Steg/Brev/Brev.tsx, src/frontend/Sider/Klage/Steg/Brev/Brevmottakere/SøkOrganisasjon.tsx, src/frontend/Sider/Klage/Steg/Brev/Brevmottakere/SøkPerson.tsx, src/frontend/hooks/useSøkOrganisasjon.ts, src/frontend/hooks/useSøkPerson.ts
=> Fjerner axios fra brevmottakere. Lager costom hooks for søketilstanden. 

src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx, src/frontend/Sider/Personoversikt/Behandlingsoversikt/FagsakOversikt.tsx, src/frontend/Sider/Personoversikt/Behandlingsoversikt/HenleggModal.tsx, src/frontend/komponenter/Modal/ModalWrapper.tsx, src/frontend/typer/toast.ts
- Unngå unødvendige henleggelser
- Kunne angi årsaker til henleggelse
=> ✨ Henlegg modal

src/frontend/Sider/Behandling/Brev/useMellomlagrignBrev.ts
Dette fikser bug der mellomlagret brev ikke ble brukt dersom man angret send til beslutter
=> 🐛 Skal hente mellomlagret brev på nytt når behandling endrer seg.

package.json, src/frontend/Sider/Behandling/Brev/Brev.tsx, src/frontend/Sider/Behandling/Brev/VariabelSerializer.tsx, src/frontend/Sider/Behandling/SettPåVent/SettPåVentInformasjon.tsx, src/frontend/Sider/Behandling/SettPåVent/TaAvVentModal.tsx, src/frontend/Sider/Behandling/Simulering/SimuleringResultatWrapper.tsx, src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Vedlegg.tsx, src/frontend/Sider/Oppgavebenk/Oppgaverad.tsx, src/frontend/Sider/Oppgavebenk/oppgaveutils.ts, src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaveliste.tsx, src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaveoversikt.tsx, src/frontend/Sider/Personoversikt/PersonoversiktInnhold.tsx, src/frontend/context/OppgaveContext.ts, src/frontend/hooks/useBrevmottakere.ts, src/frontend/hooks/useOppgaveFordeling.tsx, src/frontend/komponenter/Lenke.tsx
lint-staged virket ikke sånn at en del kode som ikke var lintet ble committet og lagt inn i main
Har også fikset diverse lint-feil
=> Fikset lint-staged som sluttet å virke

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringSøknad.tsx
=> Skal ikke vise barn det ikke er søkt for i venstrekolonne

src/frontend/Sider/Behandling/Stønadsvilkår/PassBarn/PassBarn.tsx
Dette er en tilpasning som skal gjøre det mulig å ha flere vilkår per barn.
Det skal ikke være noen funksjonelle endringer her. 
Jeg valgte å fjerne noen av spesialcasene som aldri skal inntre. Da er det bedre at ting ser knekt ut og vi får beskjed om det IMO.
=> Loop over barna i stedet for vilkårene

src/frontend/Sider/Behandling/Stønadsvilkår/PassBarn/PassBarn.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/EndreDelvilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/NyttVilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/utils.ts, src/frontend/Sider/Behandling/vilkår.ts, src/frontend/context/VilkårContext.ts, src/frontend/utils/toggles.ts
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22063
=> Periodisering av vilkår

src/frontend/Sider/Behandling/Brev/brevUtils.ts
=> Skal vise avslagbrev selv om det er revurdering

src/frontend/Sider/Behandling/Simulering/SimuleringResultatWrapper.tsx
Det er ønskelig å simulere for å vise ev. etterbetaling som gjøres
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22276
Merges etter 
* https://github.com/navikt/tilleggsstonader-sak/pull/416
=> Skal simulere også i en førstegangsbehandling.

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringSøknad.tsx, src/frontend/Sider/Behandling/Venstremeny/Oppsummering/RevurderingTag.tsx
=> added tag component for revurdering

src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/RegisterYtelserTabell.tsx, src/frontend/Sider/Personoversikt/Ytelseoversikt/Ytelseoversikt.tsx, src/frontend/Sider/Personoversikt/Ytelseoversikt/YtelserTabell.tsx, src/frontend/typer/registerytelser.ts
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22179
=> Ytelsesheader

src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx, src/frontend/Sider/Behandling/RevurderFra/RevurderFra.tsx, src/frontend/Sider/Behandling/faner.tsx, src/frontend/typer/behandling/behandling.ts, src/frontend/utils/toggles.ts, src/frontend/utils/unleashMock.ts
[Favro-kort](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22502
)
Commit-lista gir en fin oversikt over hva som gjøres i denne PR-en.
=> Revurder fra-fane

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/utils.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/validering.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/validering.tsx, src/frontend/utils/dato.ts, src/frontend/utils/periode.ts
Laget felles validering i periode-valideringen som dekker validering i revurdering. 
Regler hvis det finnes en revurderFra: 
1. Hvis det finnes noe fra før _og_ tom < revurderFra (kun tom kan redigeres), så kan ikke tom være
=> ✨ Revurder validering 

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/AktivitetVilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeVilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/EndreVilkårperiode/EndreVilkårperiodeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeRad.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/DelvilkårRadioknapper.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/JaNeiVurdering.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/LesevisningVilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/NyttVilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx, src/frontend/context/BehandlingContext.ts, src/frontend/hooks/useRevurderingAvPerioder.tsx, src/frontend/komponenter/Skjema/DateInput.tsx, src/frontend/komponenter/Skjema/MonthInput.tsx, src/frontend/utils/dato.ts
=> Revurder fra: låse felter 

src/frontend/hooks/useRevurderingAvPerioder.tsx, src/frontend/utils/periode.ts
=> Skal kunne forlenge perioder som slutter en dag før revurderFra

.github/workflows/build_dev.yaml, .github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml, package.json, src/backend/package.json
=> Felles GitHub actions

src/frontend/Sider/Behandling/faner.tsx, src/frontend/Sider/Oppgavebenk/OpprettDummyBehandling.tsx, src/frontend/typer/behandling/behandlingTema.ts, src/frontend/typer/fagsak.ts
Legger til muligheten for å opprette Dummy-behandling for Læremidler
=> Legger til muligheten for å opprette Dummy-behandling for Læremidler

src/frontend/Sider/Behandling/Stønadsvilkår/PassBarn/PassBarn.tsx, src/frontend/Sider/Behandling/Stønadsvilkår/Stønadsvilkår.tsx
Vilkår skal forholde seg til state i context og ikke det som ble hentet i første kall for å være oppdatert. Hvis ikke må man refreshe for å se endringene sine
=> 🐛 Oppdateringer på vilkår blir ikke vist

src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22796
=> 💄 Styling av behandlingstabell i saker fanen

src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingOversikt.tsx, src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx, src/frontend/hooks/useFagsakPerson.ts, src/frontend/hooks/useHentBehandlingsoversikt.ts, src/frontend/typer/behandling/behandlingoversikt.ts, src/frontend/utils/behandlingutil.ts
* Tar i bruk nytt endepunkte som inneholder liknende informasjon som før. Nå inneholder det nye også informasjon om vedtaksperioden til behandlingen.
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22783
Sak skulle også få en PR men klarte å pushe direkt til main da.. 
* https://github.com/navikt/tilleggsstonader-sak/commit/a4e3464d7abb76d511b9a57daa7c14165c95f66f
=> Behandlingsoversikt vedtaksperiode

src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettNyBehandlingModal.tsx, src/frontend/utils/toggles.ts
Co-authored-by: Eirik Vilpponen <eirik.vilpponen@nav.no
Fjerner featiure toggle sak.kan-opprette-klage .
=> Fjernet feature-toggle kanOppretteKlage

src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Aksjonsknapper.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/Stønadsperioder.tsx, src/frontend/utils/toggles.ts
Legg til knapp for å foreslå stønadsperioder. 
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22628
=> Legg til knapp for å foreslå stønadsperioder

src/backend/auth/client.ts, src/backend/auth/local.ts, src/backend/package.json, src/backend/yarn.lock
Openid-client er helt omskreven 
https://github.com/panva/openid-client/releases
https://github.com/panva/openid-client/releases/tag/v6.0.0
Burde vurdere å ta i bruk https://github.com/navikt/oasis/tree/main
=> Oppdatert til openid-client v6

package.json, yarn.lock
- Oppdatert til nyere versjon av aksel
- Fjernet en tidligere akselavhengighet som ikke lenger brukes. Den hang igjen fra det var skille mellom eksterne og interne komponenter 🤷 
Sett over en del, men kan umulig ha sjekket alt. Så om flere vil trykke seg rundt og se er det supert ⭐
=> Oppdater aksel

src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeHjelpetekst.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/hjelpetekstVurdereMålgruppe.ts, src/frontend/Sider/Klage/Steg/Formkrav/EndreFormkravVurderinger.tsx, src/frontend/Sider/Klage/Steg/Vurdering/Vurdering.tsx, src/frontend/Sider/Klage/Steg/Vurdering/VurderingLesemodus.tsx, src/frontend/Sider/Klage/typer/klagebehandling/klagebehandlingSteg.ts, src/frontend/Sider/Oppgavebenk/typer/enhet.ts, src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22976
=> Erstatter NAV med Nav då vi fra 1 nov skal bruke Nav

src/frontend/Sider/Behandling/Brev/Delmal.tsx, src/frontend/Sider/Behandling/Brev/DelmalMeny.tsx
Favro: 
- https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22792
- https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23023
=> Seksjoner som alltid skal inkluderes i brevet skal være åpne by default. Bruk sjekkboks i stedet for toggle. 

src/frontend/Sider/Oppgavebenk/Oppgaverad.tsx, src/frontend/Sider/Oppgavebenk/typer/oppgavetema.ts, src/frontend/Sider/Personoversikt/Oppgaveoversikt/Oppgaveliste.tsx
=> Fjerner oppgaveTypeTilVisningstekstSomTarHensynTilKlage

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/BrukAktivitetKnapp.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/BrukCell.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/RegisterAktivteter.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/RegisterAktivteterTabell.tsx
oppgave: https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23071
=> Inngangsvilkår bruk knapp

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/BrukAktivitetKnapp.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/RegisterAktivteter.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/RegisterAktivteterTabell.tsx
Ta ibruk registeraktivitet som variabelnavn for å tilrettelegge for flere datatyper senere
=> Ta ibruk registeraktivitet som variabelnavn

src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/RegisterYtelser.tsx
Oppgave : https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23202
=> Flyttet tekst inn i HelpText i RegisterYtelser

src/frontend/Sider/Personoversikt/Aktivitetsoversikt/Aktivitetsoversikt.tsx
Oppdaterer endepunktet for å hente register aktiviteter i  [PR 487 i sak](https://github.com/navikt/tilleggsstonader-sak/pull/487)
=> ♻️ Ta i bruk nytt endepunkt for å hente registerAktiviteter

package.json, src/backend/tsconfig.json, src/backend/webpack/webpack.development.ts, tsconfig.json, webpack/webpack.production.js, yarn.lock
Reverts navikt/tilleggsstonader-sak-frontend#607
Feiler ikke vid compile errors, reverter for å ev. fikse senere
=> Revert "Tatt i bruk esbuild-loader for raskere bygge og reload"

src/frontend/Sider/Behandling/Brev/Brev.tsx, src/frontend/Sider/Behandling/Brev/Brevmeny.tsx, src/frontend/Sider/Behandling/Brev/stønadsverdier/lagVerdier.ts, src/frontend/Sider/Behandling/Brev/stønadsverdier/lagVerdierTilsynBarn.ts, src/frontend/Sider/Behandling/Brev/stønadsverdier/verdier.ts, src/frontend/Sider/Behandling/Brev/vedtakstabell/lagVedtakstabell.ts, src/frontend/Sider/Behandling/Brev/vedtakstabell/lagVedtakstabellTilsynBarn.ts, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/VedtakOgBeregningBarnetilsyn.tsx, src/frontend/hooks/useVedtak.ts, src/frontend/typer/vedtak/vedtak.ts
Det er noen verdier som hentes ut fra vedtaket i brevet. Eks få til bedre typing et eller annet sted, eks fra backend, for å unngå sjekke behandling og vedtak. 
Mye mulig noe bedre enn dette burde lages, men foreløpig så vil det virke for å kunne legge til læremidler.
=> Brev håndtering av flere stønader

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Utdanning.tsx, src/frontend/typer/behandling/behandlingFakta/faktaUtdanning.ts
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23432
=> Vis info om er lærling eller liknende

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Utdanning.tsx, src/frontend/typer/behandling/behandlingFakta/faktaUtdanning.ts
Ønsker å spørre bruker om de har tidligere fullført vgs
=> Legg til spørsmål om har tidligere fullført vgs

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/Utdanning.tsx, src/frontend/typer/behandling/behandlingFakta/faktaUtdanning.ts
=> Samle 'erLærlingEllerLiknende' og 'harTidligereFullførtVgs' i ny type

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetLæremidler.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23674
https://github.com/user-attachments/assets/754cbd7b-2e60-4929-bde0-dd1d0d511fc4
=> 🔧 Viser bare felter for prosent og utdanningsnivå dersom en faktisk aktivitetstype er valgt

src/frontend/Sider/Behandling/Simulering/SimuleringResultatWrapper.tsx, src/frontend/Sider/Behandling/Stønadsvilkår/OppsummeringStønadsperioder.tsx, src/frontend/Sider/Behandling/Stønadsvilkår/Stønadsvilkår.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/Beregningsresultat.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgeLæremidler.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/Vedtaksperioder.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/VedtakOgBeregningLæremidler.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/vedtakLæremidlerUtils.ts, src/frontend/komponenter/Brev/stønadsverdier/lagVerdier.ts, src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabell.ts, src/frontend/typer/vedtak/vedtakLæremidler.ts, src/frontend/utils/periode.ts, src/frontend/utils/toggles.ts
Skal kunne 
- Legge inn vedtaksperioder
- Beregne hvor mye søker skal få i stønad
- Lagre ned vedtak
=> ✨ Vedtak og beregning læremidler

src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeHjelpetekst.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/målgruppe.ts
Legger tilbake koden fra PR https://github.com/navikt/tilleggsstonader-sak-frontend/pull/633 og legger til bugfix for kode som feilet ved innsending/lagring av målgruppe på inngangsvilkår
=> Legge tilbake feilende commit hvor hundre prosent sykepenger fjernes som maalgruppe for laremidler

src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/Begrunnelse/utils.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/aktivitet.ts, src/frontend/typer/behandling/behandlingFakta/faktaAktivitet.ts, src/frontend/typer/vedtak/vedtak.ts
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23719
=> Oppdater tekst: Ingen aktivitet -> Ingen relevant aktivitet

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Delvilkår/HarBrukerRettTilUtstyrsstipend.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Delvilkår/HarBrukerUtgifterTilLæremidler.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetLæremidler.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreStudienivå.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsLæremidler.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/valideringAktivitetLæremidler.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/tekstmapping.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/utils.ts
[Ny flyt for læremidler ](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23714)
❗ Avhengig av https://github.com/navikt/tilleggsstonader-sak/pull/533
**_Commit-lista skal være røddig å se på her_** 
https://github.com/user-attachments/assets/28ba3074-a200-44be-aaef-1de62b2b5218
=> ✨ Ny vurderingsflyt læremiddelvurderinger

src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx, src/frontend/Sider/Behandling/Fanemeny/HamburgermenyBehandling.tsx, src/frontend/Sider/Klage/Layout/Statusheader/HamburgermenyKlage.tsx, src/frontend/Sider/Klage/Layout/Statusheader/Statusheader.tsx, src/frontend/komponenter/Hamburgermeny/Hamburgermeny.tsx
Har tatt i bruk https://aksel.nav.no/komponenter/core/actionmenu og får fjernet en del custom kode.
Vanlig behandling
Klage
=> Erstatter egen Hamburgermeny med komponenter fra Aksel

src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgeLæremidler.tsx
Favro Oppgave- https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23735
=> Må beregne hvis man endre vedtaksperioder

src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/OpphørVedtak.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/VedtakOgBeregningLæremidler.tsx, src/frontend/typer/vedtak/vedtakLæremidler.ts
Åpne for Opphør av Læremidler i frontend
=> WIP Opphør Læremidler Frontend

src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettOrdinærBehandling.tsx
Favro- https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24012
=> gjørt settLaster til false i OpprettOrdinærBehandling

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetBarnetilsyn.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetLæremidler.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/EndreMålgruppeRad.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Stønadsperioder/StønadsperiodeRad.tsx, src/frontend/hooks/useRevurderingAvPerioder.tsx, src/frontend/utils/dato.ts
- alleFelterKanEndres er true hvis revurder fra er dagen etter fom, fordi man skal kunne utvide perioden, men man skal ikke kunne slette den
=> Lagt til boolean for om periode kan slettes i useRevurderingAvPerioder

src/frontend/Sider/Klage/Steg/Vurdering/hjemmel.ts
Skal gjøre det enklere for saksbehandler og velge rett lovhjemmel
=> 💬 Oppdater visningstekster for lovhjemmler

src/frontend/Sider/Behandling/Modal/HenleggModal.tsx, src/frontend/Sider/Klage/Komponenter/HenleggModal/HenleggModal.tsx, src/frontend/Sider/Klage/hooks/useHenleggBehandling.ts, src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingTabell.tsx, src/frontend/Sider/Personoversikt/Behandlingsoversikt/HenlagtÅrsakOgBegrunnelse.tsx, src/frontend/typer/behandling/behandlingoversikt.ts, src/frontend/typer/behandling/behandlingÅrsak.ts, src/frontend/typer/klage.ts, src/frontend/utils/behandlingutil.ts
Legg til mulighet for å kunne legge ved en begrunnelse ved henleggelse og vise denne
Favro:
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-22725
=> Henlagt begrunnelse

src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Beregningsresultat.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsynV2.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgelseTilsynBarnEllerVedtaksperioderFraForrigeBehandling.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/VedtaksperiodeRad.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Vedtaksperioder.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/VedtakBarnetilsynUtils.ts, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/VedtakOgBeregningBarnetilsyn.tsx, src/frontend/typer/vedtak/vedtakTilsynBarn.ts, src/frontend/utils/toggles.ts
Legg til mulighet for å innvilge ved bruk av vedtaksperioder for tilsyn barn. Ligger bak et feature flagg 🏴 
Lånt mye logikk fra innvilgelse læremidler og stønadsperioder. 
Mangler noe hjelpeinfo om inngangsvilkår og vilkår på vedtakssiden, men hele flyten for vedtak er nå på plass.
=> Vedtaksperiode tilsyn barn

src/frontend/Sider/Behandling/Felles/grunnlagAntallMndBakITiden.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsAktivitet.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Inngangsvilkår.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/målgruppe.ts, src/frontend/Sider/Behandling/faner.tsx, src/frontend/Sider/Oppgavebenk/OpprettDummyBehandling.tsx, src/frontend/Sider/Oppgavebenk/typer/oppgave.ts, src/frontend/context/BehandlingContext.ts, src/frontend/typer/behandling/behandlingTema.ts, src/frontend/typer/vedtak/vedtak.ts, src/frontend/utils/toggles.ts
Lagt til stønadstype for boutgifter
Lagt til mulighet for å opprette behandling
PR er mest lagd for å dokumentere endringene som trengs for en ny stønadstype og legges inn i favrooppgaven for å dokumentere
* https://github.com/navikt/tilleggsstonader-kontrakter/pull/108
* https://github.com/navikt/tilleggsstonader-soknad-api/pull/175
* https://github.com/navikt/tilleggsstonader-klage/pull/67
* https://github.com/navikt/tilleggsstonader-integrasjoner/pull/134
* https://github.com/navikt/tilleggsstonader-sak/pull/591
* https://github.com/navikt/tilleggsstonader-sak-frontend/pull/708
* https://github.com/navikt/tilleggsstonader-arena/commit/b3b487e1c66a04f5eb4cd34280df73142ee49c60
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24285
=> Lagt til boutgifter

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/Vedtaksperioder.tsx
Skal gjøre det enklere å fylle ut vedtaksperioder
=> ✨ Legg til funksjonalitet for å foreslå vedtaksperioder for tilsyn barn

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsynV2.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgelseTilsynBarnEllerVedtaksperioderFraForrigeBehandling.tsx, src/frontend/typer/vedtak/vedtakTilsynBarn.ts
Henger sammen med denne: https://github.com/navikt/tilleggsstonader-sak/pull/597
=> ♻️ Bruk vedtaksperioder direkte fra vedtaket i stedet for å utlede disse fra beregningsresultatet

src/frontend/Sider/Behandling/RevurderFra/Læremidler/VedtakshistorikkLæremidler.tsx, src/frontend/Sider/Behandling/RevurderFra/Læremidler/VedtakshistorikkLæremidlerTabellVisning.tsx, src/frontend/Sider/Behandling/RevurderFra/Læremidler/useHentFullstendigOversikt.tsx, src/frontend/Sider/Behandling/RevurderFra/VedtaksperioderRevurderFra.tsx, src/frontend/typer/vedtak/vedtakLæremidler.ts
Favro oppgave-  https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24185
=> komponenten for å vise vedtakshistorikk for revurdering av læremidler

src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabellTilsynBarn.ts, src/frontend/utils/dato.ts
Skal la N ta en titt før jeg merger
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-23918
=> Viser måned med full månedsnavn

src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgelseTilsynBarnEllerVedtaksperioderFraForrigeBehandling.tsx, src/frontend/typer/vedtak/vedtakTilsynBarn.ts
Ønsker å vise vedtaksperioder fra tidligere vedtak som er et opphør
Venter på denne: https://github.com/navikt/tilleggsstonader-sak/pull/605
=> ✨ Vis vedtaksperioder fra tidligere opphør

src/frontend/Sider/Behandling/Totrinnskontroll/FatteVedtak.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsynV2.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Felles/Begrunnelsesfelt.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Læremidler/InnvilgeVedtak/InnvilgeLæremidler.tsx, src/frontend/typer/vedtak/vedtakLæremidler.ts, src/frontend/typer/vedtak/vedtakTilsynBarn.ts
Legger til et begrunnelsesfelt for vedtaksperiodene
=> ✨ Begrunnelsesfelt for vedtaksperiodene

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/EndreAktivitetBoutgifter.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/utilsBoutgifter.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/valideringAktivitetBoutgifter.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/aktivitetBoutgifter.ts, src/frontend/hooks/useLagreVilkårperiode.ts
Dette er ikke informasjon som trengs for boutgifter. Ble kopiert fra tilsyn barn.
Slik der det ut:
=> 👔 Fjern aktivitetsdager for aktiviteter boutgifter

src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/tekstmapping.ts, src/frontend/Sider/Behandling/Inngangsvilkår/Vilkårperioder/VilkårperiodeKort/utils.ts
Ønsker å vise om aldersvilkår er oppfylt
=> ✨ Vis om aldersvilkår er oppfylt

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/StønadstypeTag.tsx, src/frontend/typer/behandling/behandlingTema.ts
Innspill fra Marie om at stønadstegen for boutgifter bør være: Bolig/overnatting
=> 💬  Endre stønadstag for boutgifter: "Boutgifter" -> "Bolig/overnatting"

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/BarnDetaljer.tsx, src/frontend/typer/behandling/behandlingFakta/faktaBarn.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24452
=> Nytt spørsmål på pass av dine barn siden

src/frontend/Sider/Behandling/RevurderFra/RevurderFra.tsx, src/frontend/Sider/Behandling/RevurderFra/RevurderFraReadMore.tsx
Ønsker å gjøre det enklere å velge rett revurder-fra dato
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24346
=> ✨ Legg til read more tekst om revurder-fra dato

src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/LesevisningVilkår.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/VisEllerEndreVilkår.tsx, src/frontend/Sider/Behandling/vilkår.ts
Ønsker å kunne registrere nullvedtak
=> ✨ Legg til mulighet for å registrere nullvedtak

src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/MålgruppeHjelpetekst.tsx
Favro-  https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24535
=> Oppdaterte hjelpetekst for målgruppe i MålgruppeHjelpetekst.tsx

src/frontend/Sider/Behandling/Vilkårvurdering/tekster.ts
Favro- https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24812
=> Lagt til nye spørsmålene i tekster

src/frontend/komponenter/Brev/stønadsverdier/lagVerdier.ts, src/frontend/typer/vedtak/vedtakBoutgifter.ts
Trengs for å få preutfylt fom og tom på vedtak i brevet
=> Map verdier for start og slutt på vedtak til brev

src/frontend/Sider/Personoversikt/Behandlingsoversikt/BehandlingOversikt.tsx, src/frontend/typer/behandling/behandlingoversikt.ts, src/frontend/typer/klage.ts
Favro-  https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-24868
=> oppdatert BehandlingOversikt.tsx for å vise boUtgifter

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/NyeOpplysningerMetadata.tsx, src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringLæremidler.tsx, src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringSøknad.tsx, src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/MetadataNyeOpplysninger.tsx, src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettNyBehandlingUtils.ts, src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/OpprettOrdinærBehandling.tsx, src/frontend/Sider/Personoversikt/Behandlingsoversikt/OpprettNyBehandling/validerNyeOpplysningerMetadata.ts, src/frontend/typer/behandling/behandling.ts, src/frontend/typer/behandling/nyeOpplysningerMetadata.ts
Legger til nye valg i modal ved opprettelse av ny behandling dersom årsak nye opplysninger er valgt. 
Viser deretter valgene i venstremeny inne på sak.
[Figma](https://www.figma.com/design/7eVA9o9YdfQi7MRuzx9wWu/TS-sak--Personoversikt?node-id=1-14629&p=f&t=WySQMmQVSbYHN0gh-0)
**Modal**
**Modal med feilmelding**
**Visning i venstremenyen**
=> Legger til felter i modal og visning i venstremenyen

src/frontend/Sider/Behandling/VedtakOgBeregning/Boutgifter/innvilgeVedtak/BeregningsresultatContainer.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Boutgifter/innvilgeVedtak/BeregningsresultatMedUtgift.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Boutgifter/innvilgeVedtak/InnvilgeBoutgifter.tsx, src/frontend/typer/vedtak/vedtakBoutgifter.ts, src/frontend/utils/toggles.ts
Ønsker å forbedre visningen av beregningsresultatet for at det skal bli enklere for SB å forstå utregningen.
Har lagt til detaljert visning for beregningsresultat for midlertidig overnatting.
🚩Visningen ligger bak et feature flagg for at Tone med venner skal teste om de liker visningen.
=> Bedre visning av beregningsresultat

src/frontend/Sider/Behandling/Vilkårvurdering/EndreVilkår/EndrePeriodeForVilkår.tsx, src/frontend/komponenter/Skjema/MånedÅrVelger/MånedVelger.tsx, src/frontend/komponenter/Skjema/MånedÅrVelger/MånedÅrVelger.tsx, src/frontend/komponenter/Skjema/MånedÅrVelger/ÅrVelger.tsx, src/frontend/utils/dato.ts, src/frontend/utils/toggles.ts
Det ble ikke ryddet i denne komponenten da den ble tatt inn fordi vi skulle teste om den skulle beholdes. Nå skal den beholdes 😎
=> 🧼 Forenkle månedsvelger og fjern feautreflag

src/frontend/Sider/Behandling/RevurderFra/Boutgifter/VedtakshistorikkBoutgifter.tsx, src/frontend/Sider/Behandling/RevurderFra/Boutgifter/useHentFullstendigOversikt.tsx, src/frontend/Sider/Behandling/RevurderFra/VedtaksperioderRevurderFra.tsx, src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversikt.tsx, src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktBoutgifter.tsx, src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktLæremidler.tsx, src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktTilsynBarn.tsx
For å bruke den nye datastrukturen til detaljerte vedtaksperioder slik at dataen er lik på tvers av personoversikten og revurdert fra siden.
_Note_
- Tenker å lage endepunkter for de andre stønadene i separate PR-er.
- Er en pågående diskusjon om hvordan tabellen skal se ut, dersom det blir endring i utseende kommer tar jeg det i egen PR og da på tvers av personoversikt og revurder fra sidene.
=> ✨Vedtaksperioder på revurdering boutgifter

src/frontend/Sider/Behandling/Felles/faktiskMålgruppe.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/målgruppe.ts, src/frontend/Sider/Behandling/Inngangsvilkår/typer/vilkårperiode/målgruppeTilFaktiskMålgruppe.ts, src/frontend/typer/registerytelser.ts
Legger til dagpenger typen som kommer fra sak slik at den kan vises på personoversikten
=> Viser dagpengeperioder under ytelser-fanen personoversikt

src/frontend/Sider/Behandling/VedtakOgBeregning/Boutgifter/innvilgeVedtak/BeregningsresultatContainer.tsx, src/frontend/komponenter/Brev/Brevmeny.tsx, src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabell.ts, src/frontend/komponenter/Brev/vedtakstabell/lagVedtakstabellBoutgifter.ts, src/frontend/utils/toggles.ts
=> 🚩 Fjern detaljert beregningsresultat toggle da dette skal alltid brukes

src/frontend/komponenter/SettPåVent/NullstillBehandlingAdvarselModal.tsx, src/frontend/komponenter/SettPåVent/SettPåVentInformasjon.tsx, src/frontend/komponenter/SettPåVent/TaAvVentKnapp.tsx, src/frontend/utils/toggles.ts
Når en fagsak har fått et vedtak i tidsrommet behandlingen var på vent, må behandlingen nullstilles, på lik linje som når revurder fra-datoen blir endret.  
Ble enig om Marie at to modaler etter hverandre gir mening i dette tilfellet.
=> Advarsel om at behandling vil resettes dersom den settes av vent 

src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversikt.tsx, src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktDagligReiseTSO.tsx, src/frontend/Sider/Personoversikt/Vedtaksperioderoversikt/VedtaksperioderOversiktDagligReiseTSR.tsx, src/frontend/typer/vedtak/vedtaksperiodeOppsummering.ts
Viser vedtaksperioder for daglig reise
=> Legger til støtte for å vise vedtaksperioder for daglig reise

src/frontend/Sider/Behandling/Inngangsvilkår/Aktivitet/Aktivitet.tsx, src/frontend/Sider/Behandling/Inngangsvilkår/Målgruppe/Målgruppe.tsx, src/frontend/Sider/Behandling/Stønadsvilkår/Boutgifter/LøpendeUtgifterEnBolig.tsx, src/frontend/Sider/Behandling/Stønadsvilkår/Boutgifter/LøpendeUtgifterToBoliger.tsx, src/frontend/Sider/Behandling/Stønadsvilkår/Boutgifter/UtgifterOvernatting.tsx, src/frontend/Sider/Behandling/Stønadsvilkår/DagligReise/StønadsvilkårDagligReise.tsx, src/frontend/Sider/Behandling/Stønadsvilkår/PassBarn/PassBarn.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/Barnetilsyn/InnvilgeVedtak/InnvilgeBarnetilsyn.tsx, src/frontend/Sider/Behandling/lenker.ts, src/frontend/komponenter/Panel/Panel.tsx, src/frontend/komponenter/VilkårPanel/RegelverkKontekstmeny.tsx, src/frontend/komponenter/VilkårPanel/VilkårPanel.tsx
[Fjerne visuelt støy
](https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-26035)
=> Skjul regelverk bak infoknapp 

src/frontend/Sider/Behandling/Venstremeny/Oppsummering/AktivitetDagligReise.tsx, src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringDagligReise.tsx, src/frontend/Sider/Behandling/Venstremeny/Oppsummering/OppsummeringSøknad.tsx, src/frontend/Sider/Behandling/Venstremeny/Oppsummering/ReiseDetajler.tsx, src/frontend/typer/behandling/behandlingFakta/behandlingFakta.ts, src/frontend/typer/behandling/behandlingFakta/faktaAktivitet.ts, src/frontend/typer/behandling/behandlingFakta/faktaReise.ts
Favro-  https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-25460
=> viser Reiser informasjon i venstre kolone

src/frontend/typer/vedtak/vedtak.ts
https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-26187
=> Lagt til årsak LØNN_I_TILTAK for et avslag.

src/frontend/Sider/Behandling/VedtakOgBeregning/DagligReise/innvilgeVedtak/BeregningDetajlerOffentligTransport.tsx, src/frontend/Sider/Behandling/VedtakOgBeregning/DagligReise/innvilgeVedtak/Beregningsresultat.tsx, src/frontend/typer/vedtak/vedtakDagligReise.ts
Favro- https://favro.com/organization/98c34fb974ce445eac854de0/4d617346d79341c7fbd9a40a?card=NAV-26243
=> Vise utregning av stønadsbelløp ved beregning av offentlig transport

src/frontend/Sider/Behandling/BehandlingTabsInnhold.tsx, src/frontend/Sider/Behandling/DetaljerteVedtaksperioderBehandling.tsx, src/frontend/Sider/Behandling/Felles/VarselVedtakIArena.tsx, src/frontend/Sider/Behandling/Vilkårvurdering/TidligereVedtaksperioder.tsx, src/frontend/komponenter/SettPåVent/SettPåVentContainer.tsx, src/frontend/utils/toggles.ts
Legger dette bak bryter for å teste i prod
=> Vedtaksperioder på behandling
